---
permalink: audit/audit-messages-and-object-lifecycle.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, log, object lifecycle, ingest, retrieve, delete, s3, swift, timing, ILM, Information lifecycle management, archive node, archive nodes 
summary: 每次载入，检索或删除对象时都会生成审核消息。您可以通过查找 API 专用的 \ （ S3 或 Swift\ ）审核消息来在审核日志中标识这些事务。 
---
= 审核消息和对象生命周期
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
每次载入，检索或删除对象时都会生成审核消息。您可以通过查找特定于 API （ S3 或 Swift ）的审核消息在审核日志中标识这些事务。

审核消息通过每个协议专用的标识符进行链接。

|===
| 协议 | 代码 


 a| 
链接 S3 操作
 a| 
S3BK （ S3 分段）和 / 或 S3KY （ S3 密钥）



 a| 
链接 Swift 操作
 a| 
WCON （ Swift 容器）和 / 或 WOBJ （ Swift 对象）



 a| 
链接内部操作
 a| 
CBID （对象的内部标识符）

|===


== 审核消息的时间

由于网格节点之间的时间差异，对象大小和网络延迟等因素，不同服务生成的审核消息的顺序可能与本节示例中所示的顺序不同。



== 信息生命周期管理策略配置

使用默认 ILM 策略（基线 2 副本），对象数据复制一次，总共复制两个副本。如果 ILM 策略需要两个以上的副本，则每个额外的副本还会另外显示一组 CBRE ， CBSE 和 SCMT 消息。有关 ILM 策略的详细信息，请参见有关通过信息生命周期管理管理对象的信息。



== 归档节点

归档节点向外部归档存储系统发送对象数据时生成的一系列审核消息与存储节点的类似，只是没有 SCMT （存储对象提交）消息。 对于对象数据的每个归档副本，系统会生成 ATCE （ Archive Object Store Begin ）和 ASCE （ Archive Object Store End ）消息。

归档节点从外部归档存储系统检索对象数据时生成的一系列审核消息与存储节点的类似，只是为每个检索到的对象数据副本生成了 ARCB （归档对象检索开始）和 Arce （归档对象检索结束）消息。

归档节点从外部归档存储系统删除对象数据时生成的一系列审核消息与存储节点的类似，只是没有 Srem （对象存储删除）消息，并且每个删除请求都有一条 AREM （归档对象删除）消息。

.相关信息
xref:../ilm/index.adoc[使用 ILM 管理对象]
