---
permalink: audit/client-write-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, client write, OVWR, SDEL, SPOS, SPUT, SUPD, WDEL, WPUT, S3, swift 
summary: 当 S3 或 Swift 客户端应用程序请求创建或修改对象时，系统会记录客户端写入审核消息。 
---
= 客户端写入审核消息
:icons: font
:imagesdir: ../media/


[role="lead"]
当 S3 或 Swift 客户端应用程序请求创建或修改对象时，系统会记录客户端写入审核消息。

|===
| 代码 | Description | 使用人 | 请参见 


 a| 
OVWR
 a| 
对象覆盖：记录一个事务，以便使用另一个对象覆盖一个对象。
 a| 
S3 客户端

Swift 客户端
 a| 
xref:ovwr-object-overwrite.adoc[OVWR ：对象覆盖]



 a| 
SDEL
 a| 
S3 delete ：记录成功的事务以删除对象或存储分段。

* 注： * 如果事务对子资源执行操作，则审核消息将包含字段 S3SR 。
 a| 
S3 客户端
 a| 
xref:sdel-s3-delete.adoc[SDEL ： S3 delete]



 a| 
SPOS
 a| 
S3 POST ：记录将对象从 AWS Glacier 存储还原到云存储池的成功事务。
 a| 
S3 客户端
 a| 
xref:spos-s3-post.adoc[SPOS ： S3 POST]



 a| 
SPUT
 a| 
S3 PUT ：记录成功的事务以创建新对象或存储分段。

* 注： * 如果事务对子资源执行操作，则审核消息将包含字段 S3SR 。
 a| 
S3 客户端
 a| 
xref:sput-s3-put.adoc[SPUT ： S3 PUT]



 a| 
SUPD
 a| 
S3 元数据已更新：记录成功的事务以更新现有对象或存储分段的元数据。
 a| 
S3 客户端
 a| 
xref:supd-s3-metadata-updated.adoc[SUPD ：已更新 S3 元数据]



 a| 
WDEL
 a| 
Swift delete ：记录成功的事务以删除对象或容器。
 a| 
Swift 客户端
 a| 
xref:wdel-swift-delete.adoc[WDEL ： Swift delete]



 a| 
WWPUT
 a| 
Swift PUT ：记录成功的事务以创建新对象或容器。
 a| 
Swift 客户端
 a| 
xref:wput-swift-put.adoc[WWPUT ： Swift PUT]

|===