---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: 在计划升级到 StorageGRID 11.6 时，您必须根据升级可能需要的时间考虑何时进行升级。此外，您还必须了解在升级的每个阶段可以执行哪些操作，哪些操作不能执行。 
---
= 估计完成升级所需的时间
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在计划升级到 StorageGRID 11.6 时，您必须根据升级可能需要的时间考虑何时进行升级。此外，您还必须了解在升级的每个阶段可以执行哪些操作，哪些操作不能执行。

完成 StorageGRID 升级所需的时间取决于多种因素，例如客户端负载和硬件性能。

下表汇总了主要升级任务，并列出了每个任务所需的大致时间。下表后面的步骤提供了一些说明，您可以使用这些说明来估计系统的升级时间。

[cols="1a,1a,1a,a"]
|===
| 升级任务 | Description | 所需大致时间 | 执行此任务期间 


 a| 
启动升级服务
 a| 
运行升级预检，分发软件文件并启动升级服务。
 a| 
每个网格节点 3 分钟，除非报告验证错误
 a| 
根据需要，您可以在计划的升级维护窗口之前手动运行升级预检。



 a| 
升级网格节点（主管理节点）
 a| 
主管理节点将停止，升级并重新启动。
 a| 
30 分钟到 1 小时，其中 SG100 和 SG1000 设备节点最需要时间。
 a| 
您无法访问主管理节点。系统会报告连接错误，您可以忽略这些错误。



 a| 
升级网格节点（所有其他节点）
 a| 
所有其他网格节点上的软件将按照您批准节点的顺序进行升级。系统中的每个节点将逐个关闭，每个节点将停机几分钟。
 a| 
每个节点 15 分钟到 1 小时，设备节点所需时间最多

* 注： * 对于设备节点， StorageGRID 设备安装程序会自动更新到最新版本。
 a| 
* 请勿更改网格配置。
* 请勿更改审核级别配置。
* 请勿更新 ILM 配置。
* 系统会阻止您执行其他维护过程，例如修补程序，停用或扩展。
+
* 注： * 如果需要执行恢复，请联系技术支持。





 a| 
启用功能
 a| 
新版本的新功能已启用。
 a| 
不到 5 分钟
 a| 
* 请勿更改网格配置。
* 请勿更改审核级别配置。
* 请勿更新 ILM 配置。
* 您不能执行其他维护操作步骤 。




 a| 
升级数据库
 a| 
升级过程会检查每个节点，以验证不需要更新 Cassandra 数据库。
 a| 
每个节点 10 秒或整个网格几分钟
 a| 
从 StorageGRID 11.5 升级到 11.5 不需要升级 Cassandra 数据库；但是， Cassandra 服务将在每个存储节点上停止并重新启动。

对于未来的 StorageGRID 功能版本， Cassandra 数据库更新步骤可能需要几天时间才能完成。



 a| 
最终升级步骤
 a| 
此时将删除临时文件，并完成到新版本的升级。
 a| 
5 分钟
 a| 
完成 * 最终升级步骤 * 任务后，您可以执行所有维护过程。

|===
.步骤
. 估计升级所有网格节点所需的时间。
+
.. 将 StorageGRID 系统中的节点数乘以每个节点 1 小时。
+
一般来说，设备节点的升级时间比基于软件的节点要长。

.. 此时再增加 1 小时，以说明下载 ` 。 upgrade` 文件，运行预检验证以及完成最终升级步骤所需的时间。


. 如果您使用的是 Linux 节点，请为每个节点添加 15 分钟的时间，以考虑下载和安装 RPM 或 Deb 软件包所需的时间。
. 通过添加步骤 1 和步骤 2 的结果来计算升级的总估计时间。




== 示例：升级到 StorageGRID 11.6 的估计时间

假设您的系统有 14 个网格节点，其中 8 个是 Linux 节点。

. 将 14 乘以每个节点 1 小时。
. 另外，还需要 1 小时的时间来说明下载，预检和最终步骤。
+
升级所有节点的估计时间为 15 小时。

. 将每个节点的 8 乘以 15 分钟，以说明在 Linux 节点上安装 RPM 或 Deb 软件包的时间。
+
此步骤的估计时间为 2 小时。

. 将这些值相加。
+
您应在长达 17 小时的时间内完成系统到 StorageGRID 11.0.0 的升级。


