---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: 您必须了解 StorageGRID 系统在升级期间会受到什么影响。 
---
= 升级期间对系统的影响
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须了解 StorageGRID 系统在升级期间会受到什么影响。



== StorageGRID 升级不会造成系统中断

StorageGRID 系统可以在整个升级过程中从客户端应用程序载入和检索数据。在升级期间，网格节点会一次关闭一个，因此，目前并非所有网格节点都不可用。

要保证持续可用性，您必须确保使用适当的 ILM 策略以冗余方式存储对象。此外，您还必须确保将所有外部 S3 或 Swift 客户端配置为向以下客户端之一发送请求：

* 配置为高可用性（ HA ）组的 StorageGRID 端点
* 高可用性第三方负载平衡器
* 每个客户端具有多个网关节点
* 每个客户端具有多个存储节点




== 设备固件已升级

在 StorageGRID 11.6 升级期间：

* 所有 StorageGRID 设备节点都会自动升级到 StorageGRID 设备安装程序固件版本 3.6 。
* SG6060 和 SGF6024 设备会自动升级到 BIOS 固件版本 3B07.EX 和 BMC 固件版本 BMC 3.93.07 。
* SG100 和 SG1000 设备会自动升级到 BIOS 固件版本 3B12.EC 和 BMC 固件版本 4.67.07 。




== 可能会触发警报

服务启动和停止以及 StorageGRID 系统作为混合版本环境运行时（某些网格节点运行早期版本，而其他网格节点已升级到更高版本），可能会触发警报。升级完成后，可能会触发其他警报。

例如，服务停止时，您可能会看到 * 无法与节点 * 通信警报；或者，如果某些节点已升级到 StorageGRID 11.6 ，但其他节点仍在运行 StorageGRID 11.5 ，则可能会看到 * Cassandra communication error* 警报。通常，这些警报将在升级完成后清除。

在升级到 StorageGRID 11.6 期间停止存储节点时，可能会触发 "ILM placement unableableableable" 警报。升级完成后，此警报可能会持续 1 天。

如果对存储卷水印使用自定义值，则升级完成后可能会触发 * 低只读水印覆盖 * 警报。请参见 xref:../monitor/troubleshoot-low-watermark-alert.adoc[对低只读水印覆盖警报进行故障排除] 了解详细信息。

升级完成后，您可以从网格管理器信息板中选择 * 最近解决的警报 * 或 * 当前警报 * 来查看任何与升级相关的警报。



== 系统会生成许多 SNMP 通知

请注意，在升级期间停止并重新启动网格节点时，可能会生成大量 SNMP 通知。要避免出现过多通知，请在开始升级之前取消选中 * 启用 SNMP 代理通知 * 复选框（ * 配置 * > * 监控 * > * SNMP 代理 * ）以禁用 SNMP 通知。然后，在升级完成后重新启用通知。



== 配置更改受限


NOTE: 受限配置更改的列表可能会随版本而异。升级到另一个 StorageGRID 版本时，请参阅相应升级说明中的列表。

直到 * 启用新功能 * 任务完成：

* 请勿更改任何网格配置。
* 请勿更改审核级别配置或配置外部系统日志服务器。
* 请勿启用或禁用任何新功能。
* 请勿更新 ILM 配置。否则，您可能会遇到不一致的意外 ILM 行为。
* 请勿应用修补程序或恢复网格节点。
* 升级到 StorageGRID 11.6 时，您无法管理 HA 组， VLAN 接口或负载平衡器端点。


完成 * 最终升级步骤 * 任务之前：

* 请勿执行扩展操作步骤 。
* 请勿执行停用操作步骤 。




== 您不能从租户管理器查看存储分段详细信息或管理存储分段

在升级到 StorageGRID 11.6 期间（即，当系统作为混合版本环境运行时），您无法使用租户管理器查看存储分段详细信息或管理存储分段。租户管理器中的 " 分段 " 页面显示以下错误之一：

* "`在升级到 11.6. 时不能使用此 API 。` "
* "`升级到 11.6.` 时，您无法在租户管理器中查看存储分段版本控制详细信息。 "


升级到 11.6 后，此错误将得以解决。

在执行 11.6 升级期间，请使用以下工具查看存储分段详细信息或管理存储分段，而不是使用租户管理器：

* 要对存储分段执行标准 S3 操作，请使用 S3 REST API 或租户管理 API 。
* 要对存储分段执行 StorageGRID 自定义操作（例如，查看和修改存储分段一致性级别，启用或禁用上次访问时间更新或配置搜索集成），请使用租户管理 API 。


请参见 xref:../tenant/understanding-tenant-management-api.adoc[了解租户管理 API] 和 xref:../s3/index.adoc[使用 S3] 有关说明，请参见。
