---
permalink: upgrade/obtaining-required-materials-for-software-upgrade.html 
sidebar: sidebar 
keywords: upgrade, requirements, rhel, red hat, linux, centOS, ubuntu, debian 
summary: 在开始软件升级之前，您必须获取所有必需的材料，才能成功完成升级。 
---
= 获取软件升级所需的材料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在开始软件升级之前，您必须获取所有必需的材料，才能成功完成升级。

[cols="1a,3a"]
|===
| 项目 | 注释： 


 a| 
StorageGRID 升级文件
 a| 
 the StorageGRID upgrade files 连接到您的服务笔记本电脑。



 a| 
服务笔记本电脑
 a| 
服务笔记本电脑必须具有：

* 网络端口
* SSH 客户端（例如 PuTTY ）




 a| 
xref:../admin/web-browser-requirements.adoc[支持的 Web 浏览器]
 a| 
每个 StorageGRID 版本的浏览器支持通常会发生变化。确保您的浏览器与新的 StorageGRID 版本兼容。



 a| 
恢复软件包（` .zip` ）文件
 a| 
 the Recovery Package 升级之前，请将此文件保存在安全位置。通过恢复包文件，您可以在发生故障时还原系统。



 a| 
`passwords.txt` file
 a| 
该文件包含在上述软件包中，该软件包是恢复软件包 ` .zip` 文件的一部分。您必须获取最新版本的恢复软件包。



 a| 
配置密码短语
 a| 
首次安装 StorageGRID 系统时，系统会创建并记录密码短语。配置密码短语未列在 `passwords.txt` 文件中。



 a| 
相关文档
 a| 
* xref:../release-notes/index.adoc[发行说明] 对于 StorageGRID 11.6.在开始升级之前，请务必仔细阅读这些内容。
* 说明 xref:../admin/index.adoc[管理 StorageGRID]。
* 如果要升级 Linux 部署，请参见适用于您的 Linux 平台的 StorageGRID 安装说明：
+
** xref:../rhel/index.adoc[安装 Red Hat Enterprise Linux 或 CentOS]
** xref:../ubuntu/index.adoc[安装 Ubuntu 或 Debian]


* 根据需要提供其他 StorageGRID 文档。


|===


== 下载 StorageGRID 升级文件

您必须下载一个或多个文件，具体取决于节点的安装位置。

* * 所有平台 * ： ` 。 upgrade` file


如果在 Linux 主机上部署了任何节点，则还必须下载 RPM 或 Deb 归档文件，此文件将在开始升级之前安装：

* * Red Hat Enterprise Linux 或 CentOS* ：附加 RPM 文件（` .zip` 或 ` .tgz` ）
* * Ubuntu 或 Debian * ：一个额外的 Deb 文件（` .zip` 或 ` .tgz` ）


.步骤
. 转至 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 下载： StorageGRID"^]。
. 选择用于下载最新版本的按钮，或者从下拉菜单中选择其他版本并选择 * 执行 * 。
+
StorageGRID 软件版本采用以下格式： 11._x.y_ 。StorageGRID 修补程序采用以下格式： 11._x.y.z_ 。

. 使用您的 NetApp 帐户的用户名和密码登录。
. 如果显示 Caution/MustRead 语句，请阅读该语句并选中复选框。
+
如果此版本需要修补程序，则会显示此语句。

. 阅读最终用户许可协议，选中复选框，然后选择 * 接受并继续 * 。
+
此时将显示选定版本的下载页面。此页面包含三列：

+
** 安装 StorageGRID
** 升级 StorageGRID
** StorageGRID 设备的支持文件


. 在 * 升级 StorageGRID * 列中，选择并下载 ` 。 upgrade` archive 。
+
每个平台都需要 ` 。 upgrade` archive 。

. 如果在 Linux 主机上部署了任何节点，请同时以 ` .tgz` 或 ` .zip` 格式下载 RPM 或 Deb 归档。如果您在服务笔记本电脑上运行 Windows ，请选择 ` .zip` 文件。
+
** Red Hat Enterprise Linux 或 CentOS + `StorageGRID-Webscale -_version_-RPM-_uniqueID_.zip` + `StorageGRID-Webscale -_version_-RPM-_uniqueID_.tgz`
** Ubuntu 或 Debian + `StorageGRID-Webscale -_version_-Deb-_uniqueID_.zip` + `StorageGRID-Webscale -_version_-Deb-_uniqueID_.tgz`
+

NOTE: SG100 或 SG1000 不需要其他文件。







== 下载恢复包

通过恢复包文件，您可以在发生故障时还原 StorageGRID 系统。在对 StorageGRID 系统进行网格拓扑更改之前或升级软件之前，请下载当前的恢复软件包文件。然后，在更改网格拓扑或升级软件后下载恢复包的新副本。

.您需要什么？ #8217 ；将需要什么
* 您必须使用登录到网格管理器 xref:../admin/web-browser-requirements.adoc[支持的 Web 浏览器]。
* 您必须具有配置密码短语。
* 您必须具有特定的访问权限。


.步骤
. 选择 * 维护 * > * 系统 * > * 恢复包 * 。
. 输入配置密码短语，然后选择 * 开始下载 * 。
+
下载将立即开始。

. 下载完成后：
+
.. 打开 ` .zip` 文件。
.. 确认其中包含 `gpt-backup` 目录和内侧 ` .zip` 文件。
.. 提取内部 ` .zip` 文件。
.. 确认您可以打开 `passwords.txt` 文件。


. 将下载的恢复软件包文件（` .zip` ）复制到两个安全的单独位置。
+

IMPORTANT: 恢复包文件必须受到保护，因为它包含可用于从 StorageGRID 系统获取数据的加密密钥和密码。


