---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: 在开始升级之前，您必须确认先前版本的 StorageGRID 当前已安装应用了最新可用的修补程序。 
---
= 验证已安装的 StorageGRID 版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在开始升级之前，您必须确认先前版本的 StorageGRID 当前已安装应用了最新可用的修补程序。

.关于此任务
在升级到 StorageGRID 11.5 之前，网格必须安装 StorageGRID 11.5 。如果您当前使用的是早期版本的 StorageGRID ，则必须安装所有先前的升级文件及其最新的修补程序（强烈建议），直到网格的当前版本为 StorageGRID 11.5. _x.y_ 为止。

中显示了一个可能的升级路径 <<示例：从 11.3.0.8 版升级到 StorageGRID 11.5,示例>>。


IMPORTANT: NetApp 强烈建议您在升级到下一个版本之前对每个 StorageGRID 版本应用最新的修补程序，同时对安装的每个新版本应用最新的修补程序。在某些情况下，您必须应用修补程序以避免数据丢失的风险。请参见 https://["NetApp 下载： StorageGRID"^] 以及每个修补程序的发行说明以了解更多信息。

请注意，您可以运行一个脚本，以便一步从 11.3.1.0.3+ 更新到 11.4.0._y_ ，一步从 11.4.0.7+ 更新到 11.5.0._y_ 。请参见 https://["NetApp 知识库：如何为 StorageGRID 运行组合式主要升级和修补程序脚本"^]。

.步骤
. 使用登录到网格管理器 xref:../admin/web-browser-requirements.adoc[支持的 Web 浏览器]。
. 从网格管理器的顶部，选择 * 帮助 * > * 关于 * 。
. 验证 * 版本 * 是否为 11.5. _x.y_ 。
+
在 StorageGRID 11.5. _x.y_ 版本号中：

+
** 主要版本 * 的 _x_ 值为 0 （ 11.5.0 ）。
** 如果应用了一个 * 热修补程序 * ，则该热修补程序 * 具有 _y_ 值（例如 11.5.0.1 ）。


. 如果 * 版本 * 不是 11.5. _x.y_ ，请转至 https://["NetApp 下载： StorageGRID"^] 下载每个先前版本的文件，包括每个版本的最新修补程序。
. 获取下载的每个版本的升级说明。然后，对该版本执行软件升级操作步骤 ，并应用该版本的最新修补程序（强烈建议）。
+
请参见 xref:../maintain/storagegrid-hotfix-procedure.adoc[StorageGRID 热修补程序操作步骤]。





== 示例：从 11.3.0.8 版升级到 StorageGRID 11.5

以下示例显示了从 StorageGRID 11.3.0.8 版升级到 11.5 版以准备 StorageGRID 11.5 版的步骤。


IMPORTANT: 或者，您也可以运行一个脚本来合并步骤 2 和 3 （从 11.3.1.0.13 更新到 11.4.0._y_ ）以及合并步骤 4 和 5 （从 11.4.0.7+ 更新到 11.5.0._y_ ）。请参见 https://["NetApp 知识库：如何为 StorageGRID 运行组合式主要升级和修补程序脚本"^]。

按以下顺序下载并安装软件，以便为您的系统做好升级准备：

. 应用最新的 StorageGRID 11.3.0._y_ 修补程序。
. 升级到 StorageGRID 11.4.0 主要版本。
. 应用最新的 StorageGRID 11.4.0._y_ 修补程序。
. 升级到 StorageGRID 11.5.0 主要版本。
. 应用最新的 StorageGRID 11.5.0._y_ 修补程序。

