---
permalink: ubuntu/configuring-host-storage.html 
sidebar: sidebar 
keywords: how to configure host storage 
summary: 您必须为每个主机分配块存储卷。 
---
= 配置主机存储
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须为每个主机分配块存储卷。

您已阅读以下主题，其中提供了完成此任务所需的信息：

xref:storage-and-performance-requirements.adoc[存储和性能要求]

xref:node-container-migration-requirements.adoc[节点容器迁移要求]

在将块存储卷（ LUN ）分配给主机时，请使用 `S存储要求` 中的表确定以下内容：

* 每个主机所需的卷数（根据要在该主机上部署的节点的数量和类型）
* 每个卷的存储类别（即系统数据或对象数据）
* 每个卷的大小


在主机上部署 StorageGRID 节点时，您将使用此信息以及 Linux 为每个物理卷分配的永久性名称。


NOTE: 您无需对其中任何卷进行分区，格式化或挂载；您只需确保这些卷对主机可见即可。

在编写卷名称列表时，请避免使用 "`raw` " 特殊设备文件（例如，` /dev/sdb` ）。这些文件可能会在主机重新启动后发生更改，从而影响系统的正常运行。如果您使用的是 iSCSI LUN 和设备映射程序多路径，请考虑在 ` /dev/mapper` 目录中使用多路径别名，尤其是在 SAN 拓扑包含指向共享存储的冗余网络路径时。或者，您也可以在 ` /dev/disk/by-path/` 下使用系统创建的软链接作为永久性设备名称。

例如：

[listing]
----
ls -l
$ ls -l /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:00:07.1-ata-2 -> ../../sr0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:1:0 -> ../../sdb
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:2:0 -> ../../sdc
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:3:0 -> ../../sdd
----
每个安装的结果会有所不同。

为每个块存储卷分配友好名称，以简化初始 StorageGRID 安装和未来维护过程。如果使用设备映射程序多路径驱动程序对共享存储卷进行冗余访问，则可以在 ` /etc/multipath.conf` 文件中使用 `alias` 字段。

例如：

[listing]
----
multipaths {
     multipath {
          wwid 3600a09800059d6df00005df2573c2c30
          alias docker-storage-volume-hostA
     }
     multipath {
          wwid 3600a09800059d6df00005df3573c2c30
          alias sgws-adm1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df4573c2c30
          alias sgws-adm1-audit-logs
     }
     multipath {
          wwid 3600a09800059d6df00005df5573c2c30
          alias sgws-adm1-tables
     }
     multipath {
          wwid 3600a09800059d6df00005df6573c2c30
          alias sgws-gw1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-rangedb-0
     }
     …
----
这样就会对别名进行发生原因 ，使其显示为主机上的 ` /dev/mapper` 目录中的块设备，从而可以在配置或维护操作需要指定块存储卷时指定一个易于验证的友好名称。


NOTE: 如果要设置共享存储以支持 StorageGRID 节点迁移并使用设备映射程序多路径功能，则可以在所有主机上创建并安装通用的 ` /etc/multipath.conf` 。只需确保在每个主机上使用不同的 Docker 存储卷即可。使用别名并将目标主机名包含在每个 Docker 存储卷 LUN 的别名中，这一点便于记住，建议这样做。

xref:storage-and-performance-requirements.adoc[存储和性能要求]

xref:node-container-migration-requirements.adoc[节点容器迁移要求]
