---
permalink: ubuntu/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: how to download ubuntu or debian installation files 
summary: 您必须下载 StorageGRID 安装归档并提取所需文件。 
---
= 下载并提取 StorageGRID 安装文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须下载 StorageGRID 安装归档并提取所需文件。

.步骤
. 转至 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["StorageGRID 的 "NetApp 下载 " 页面"^]。
. 选择用于下载最新版本的按钮，或者从下拉菜单中选择其他版本并选择 * 执行 * 。
. 使用您的 NetApp 帐户的用户名和密码登录。
. 如果显示 Caution/MustRead 语句，请阅读该语句并选中复选框。
+

IMPORTANT: 安装 StorageGRID 版本后，您必须应用任何所需的修补程序。有关详细信息，请参见 xref:../maintain/storagegrid-hotfix-procedure.adoc[恢复和维护说明中的热修补程序操作步骤]

. 阅读最终用户许可协议，选中复选框，然后选择 * 接受并继续 * 。
+
此时将显示选定版本的下载页面。此页面包含三列：

. 在 * 安装 StorageGRID * 列中，为 Ubuntu 或 Debian 选择 .tgz 或 .zip 文件。
+

NOTE: 如果您在服务笔记本电脑上运行 Windows ，请选择 ` .zip` 文件。

. 保存并提取归档文件。
. 从以下列表中选择所需的文件。
+
所需的文件集取决于您规划的网格拓扑以及如何部署 StorageGRID 网格。

+

NOTE: 表中列出的路径与提取的安装归档所安装的顶级目录相对。



[cols="1a,1a"]
|===
| 路径和文件名 | Description 


| /debs/README  a| 
一个文本文件，用于描述 StorageGRID 下载文件中包含的所有文件。



| ./debs/NLF000000.txt  a| 
非生产 NetApp 许可证文件，可用于测试和概念验证部署。



| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
用于在 Ubuntu 或 Debian 主机上安装 StorageGRID 节点映像的 Deb 软件包。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
文件 ` /debs/storagegrid-webscale-images-version-SHA.deb` 的 MD5 校验和。



| ./debs/storagegrid-webscale-service-version-SHA.deb  a| 
用于在 Ubuntu 或 Debian 主机上安装 StorageGRID 主机服务的 Deb 软件包。



| 部署脚本工具 | Description 


| ./debs/configure-storagegrid.py  a| 
一种用于自动配置 StorageGRID 系统的 Python 脚本。



| ./debs/configure-sga.py  a| 
一种用于自动配置 StorageGRID 设备的 Python 脚本。



| ./debs/storagegrid-ssoauth.py  a| 
一个示例 Python 脚本，启用单点登录后，您可以使用该脚本登录到网格管理 API 。



| ./debs/configure-storaggrid.sample.json  a| 
与 `configure-storaggrid.py` 脚本结合使用的示例配置文件。



| ./debs/configure-storaggrid.blank.json  a| 
用于 `configure-storaggrid.py` 脚本的空配置文件。



| ./debs/Extras / Ansible  a| 
用于为 StorageGRID 容器部署配置 Ubuntu 或 Debian 主机的 Ansible 角色示例和攻略手册。您可以根据需要自定义角色或攻略手册。



| ./debs/ExtrS/API 架构  a| 
StorageGRID 的 API 架构。

* 注意 * ：在执行升级之前，如果您没有用于升级兼容性测试的非生产 StorageGRID 环境，则可以使用这些架构确认为使用 StorageGRID 管理 API 编写的任何代码都与新的 StorageGRID 版本兼容。

|===
xref:../maintain/index.adoc[恢复和维护]
