---
permalink: ubuntu/planning-and-preparation.html 
sidebar: sidebar 
keywords: how to prepare for ubuntu or debian installation 
summary: 在部署网格节点和配置 StorageGRID 网格之前，您必须熟悉完成操作步骤 的步骤和要求。 
---
= 安装之前（ Ubuntu 或 Debian ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在部署网格节点和配置 StorageGRID 网格之前，您必须熟悉完成操作步骤 的步骤和要求。

StorageGRID 部署和配置过程假定您熟悉 StorageGRID 系统的架构和操作。

您可以一次部署一个或多个站点；但是，所有站点必须满足至少有三个存储节点的最低要求。

在开始安装 StorageGRID 之前，您必须：

* 了解 StorageGRID 的计算要求，包括每个节点的最低 CPU 和 RAM 要求。
* 了解 StorageGRID 如何支持多个网络以实现流量隔离，安全性和管理便利性，并计划要连接到每个 StorageGRID 节点的网络。
+
请参见 StorageGRID 网络连接准则。

* 了解每种类型的网格节点的存储和性能要求。
* 确定一组服务器（物理服务器，虚拟服务器或两者），这些服务器可在聚合中提供足够的资源来支持您计划部署的 StorageGRID 节点的数量和类型。
* 如果要在不中断任何服务的情况下对物理主机执行计划内维护，请了解节点迁移的要求。
* 提前收集所有网络信息。除非使用 DHCP ，否则请收集要分配给每个网格节点的 IP 地址以及要使用的域名系统（ DNS ）和网络时间协议（ NTP ）服务器的 IP 地址。
* 按照规格安装，连接和配置所有必需的硬件，包括任何 StorageGRID 设备。
+

NOTE: StorageGRID 安装操作步骤 中不包含特定于硬件的安装和集成说明。要了解如何安装 StorageGRID 设备，请参见适用于您的设备的安装和维护说明。

* 确定要使用的可用部署和配置工具。


.相关信息
xref:../network/index.adoc[网络连接准则]

xref:../sg100-1000/index.adoc[SG100 和 SG1000 服务设备]

xref:../sg6000/index.adoc[SG6000 存储设备]

xref:../sg5700/index.adoc[SG5700 存储设备]

xref:../sg5600/index.adoc[SG5600 存储设备]

xref:node-container-migration-requirements.adoc[节点容器迁移要求]
