---
permalink: harden/hardening-guidelines-for-software-upgrades.html 
sidebar: sidebar 
keywords: Hardening guidelines, upgrades 
summary: 您必须使 StorageGRID 系统和相关服务保持最新，以抵御攻击。 
---
= 软件升级的强化准则
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须使 StorageGRID 系统和相关服务保持最新，以抵御攻击。



== 升级到 StorageGRID 软件

您应尽可能将 StorageGRID 软件升级到最新的主要版本或先前的主要版本。使 StorageGRID 保持最新有助于缩短已知漏洞处于活动状态的时间，并减少整体攻击面。此外， StorageGRID 的最新版本通常包含早期版本中不包括的安全强化功能。

如果需要修补程序， NetApp 会优先为最新版本创建更新。某些修补程序可能与早期版本不兼容。

要下载最新的 StorageGRID 版本和修补程序，请转到 StorageGRID 软件下载页面。有关升级 StorageGRID 软件的分步说明，请参见有关升级 StorageGRID 的说明。有关应用修补程序的说明，请参见恢复和维护说明。



== 升级到外部服务

外部服务可能存在间接影响 StorageGRID 的漏洞。您应确保 StorageGRID 所依赖的服务保持最新。这些服务包括 LDAP ， KMS （或 KMIP 服务器）， DNS 和 NTP 。

使用 NetApp 互操作性表工具可获取受支持版本的列表。



== 升级到虚拟机管理程序

如果您的 StorageGRID 节点正在 VMware 或其他虚拟机管理程序上运行，则必须确保虚拟机管理程序软件和固件是最新的。

使用 NetApp 互操作性表工具可获取受支持版本的列表。



== 升级到 Linux 节点

如果 StorageGRID 节点使用的是 Linux 主机平台，则必须确保将安全更新和内核更新应用于主机操作系统。此外，如果存在固件更新，则必须将这些更新应用于容易受到影响的硬件。

使用 NetApp 互操作性表工具可获取受支持版本的列表。

https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 下载： StorageGRID"^]

xref:../upgrade/index.adoc[升级软件]

xref:../maintain/index.adoc[恢复和维护]

https://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^]
