---
permalink: tenant/changing-consistency-level.html 
sidebar: sidebar 
keywords: how to change tenant consistency level, read after new write, read-after-new-write, strong site, strong-site, strong global, strong-global 
summary: 如果您使用的是 S3 租户，则可以使用租户管理器或租户管理 API 来更改对 S3 分段中的对象执行的操作的一致性控制。 
---
= 更改一致性级别
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用的是 S3 租户，则可以使用租户管理器或租户管理 API 来更改对 S3 分段中的对象执行的操作的一致性控制。

.您需要什么？ #8217 ；将需要什么
* 您必须使用登录到租户管理器 xref:../admin/web-browser-requirements.adoc[支持的 Web 浏览器]。
* 您必须属于具有 " 管理所有分段 " 或 " 根访问 " 权限的用户组。这些权限将覆盖组或存储分段策略中的权限设置。请参见 xref:tenant-management-permissions.adoc[租户管理权限]。


一致性级别可以在对象的可用性与这些对象在不同存储节点和站点之间的一致性之间进行权衡。通常，您应该对存储分段使用 * 读 - 后 - 新 - 写 * 一致性级别。如果 * 读后新写入 * 一致性级别不符合客户端应用程序的要求，您可以通过设置存储分段一致性级别或使用 `consistency Control` 标头来更改一致性级别。`consistency Control` 标题将覆盖存储分段一致性级别。


NOTE: 更改存储分段的一致性级别时，只会保证更改后载入的对象符合修订后的级别。

.步骤
. 选择 * 存储（ S3 ） * > * 分段 * 。
. 从列表中选择存储分段名称。
+
此时将显示存储分段详细信息页面。

. 选择 * 分段选项 * > * 一致性级别 * 。
. 为此存储分段中的对象选择一个一致性级别。
+
[cols="1a,3a"]
|===
| 一致性级别 | Description 


 a| 
全部
 a| 
所有节点都会立即接收数据，否则请求将失败。



 a| 
强大的全局功能
 a| 
保证所有站点中所有客户端请求的写入后读一致性。



 a| 
强大的站点
 a| 
保证站点内所有客户端请求的写入后读一致性。



 a| 
Read-after-new-write （默认）
 a| 
为新对象提供读写一致性，并最终为对象更新提供一致性。提供高可用性和数据保护保证。最符合 Amazon S3 一致性保证。

* 注意： * 如果应用程序尝试对不存在的密钥执行 head 或 get 操作，请将一致性级别设置为 * 可用 * ，除非您需要 Amazon S3 一致性保证。否则，如果一个或多个存储节点不可用，则可能会出现大量 500 个内部服务器错误。



 a| 
可用（机头或 GET 操作的最终一致性）
 a| 
行为与 * 读后新写入 * 一致性级别相同，但可为 head 和 get 操作提供最终一致性。如果存储节点不可用，则与 * 读后新写入 * 相比，可为机头和 GET 操作提供更高的可用性。与 Amazon S3 对机头和 GET 操作的一致性保证不同。

|===
. 选择 * 保存更改 * 。

