---
permalink: tenant/managing-groups.html 
sidebar: sidebar 
keywords: how to manage groups 
summary: 您可以为用户组分配权限，以控制租户用户可以执行的任务。您可以从身份源（例如 Active Directory 或 OpenLDAP ）导入联合组，也可以创建本地组。 
---
= 管理组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以为用户组分配权限，以控制租户用户可以执行的任务。您可以从身份源（例如 Active Directory 或 OpenLDAP ）导入联合组，也可以创建本地组。


IMPORTANT: 如果为 StorageGRID 系统启用了单点登录（ SSO ），则本地用户将无法登录到租户管理器，但他们可以根据组权限访问 S3 和 Swift 资源。



== 租户管理权限

在创建租户组之前，请考虑要分配给该组的权限。租户管理权限用于确定用户可以使用租户管理器或租户管理 API 执行的任务。一个用户可以属于一个或多个组。如果用户属于多个组，则权限是累积的。

要登录到租户管理器或使用租户管理 API ，用户必须属于至少具有一个权限的组。所有可以登录的用户均可执行以下任务：

* 查看信息板
* 更改自己的密码（适用于本地用户）


对于所有权限，组的访问模式设置将确定用户是否可以更改设置并执行操作，或者是否只能查看相关设置和功能。


NOTE: 如果用户属于多个组，并且任何组设置为只读，则用户将对所有选定设置和功能具有只读访问权限。

您可以为组分配以下权限。请注意， S3 租户和 Swift 租户具有不同的组权限。由于缓存，更改可能需要长达 15 分钟才能生效。

[cols="1a,3a"]
|===
| 权限 | Description 


 a| 
根访问
 a| 
提供对租户管理器和租户管理 API 的完全访问权限。

* 注： * Swift 用户必须具有 root 访问权限才能登录到租户帐户。



 a| 
管理员
 a| 
仅限 Swift 租户。提供对此租户帐户的 Swift 容器和对象的完全访问权限

* 注： * Swift 用户必须具有 Swift 管理员权限才能使用 Swift REST API 执行任何操作。



 a| 
管理您自己的 S3 凭据
 a| 
仅限 S3 租户。允许用户创建和删除自己的 S3 访问密钥。没有此权限的用户不会看到 * 存储（ S3 ） * > * 我的 S3 访问密钥 * 菜单选项。



 a| 
管理所有分段
 a| 
* S3 租户：允许用户使用租户管理器和租户管理 API 创建和删除 S3 存储分段，并管理租户帐户中所有 S3 存储分段的设置，而不管 S3 存储分段或组策略如何。
+
没有此权限的用户不会看到 * 分段 * 菜单选项。

* Swift 租户：允许 Swift 用户使用租户管理 API 控制 Swift 容器的一致性级别。


* 注意： * 您只能通过租户管理 API 为 Swift 组分配 " 管理所有分段 " 权限。您不能使用租户管理器将此权限分配给 Swift 组。



 a| 
管理端点
 a| 
仅限 S3 租户。允许用户使用租户管理器或租户管理 API 创建或编辑端点，这些端点用作 StorageGRID 平台服务的目标。

没有此权限的用户不会看到 * 平台服务端点 * 菜单选项。

|===
xref:../s3/index.adoc[使用 S3]

xref:../swift/index.adoc[使用 Swift]
