---
permalink: tenant/what-platform-services-are.html 
sidebar: sidebar 
keywords: what are platform services 
summary: StorageGRID 平台服务可以帮助您实施混合云战略。 
---
= 什么是平台服务？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 平台服务可以帮助您实施混合云战略。

如果您的租户帐户允许使用平台服务，则可以为任何 S3 存储分段配置以下服务：

* * CloudMirror 复制 * ： xref:understanding-cloudmirror-replication-service.adoc[StorageGRID CloudMirror 复制服务] 用于将特定对象从 StorageGRID 存储分段镜像到指定的外部目标。
+
例如，您可以使用 CloudMirror 复制将特定客户记录镜像到 Amazon S3 ，然后利用 AWS 服务对数据执行分析。

+

NOTE: 如果源存储分段启用了 S3 对象锁定，则不支持 CloudMirror 复制。

* * 通知 * ： xref:understanding-notifications-for-buckets.adoc[每个存储分段的事件通知] 用于向指定的外部 Amazon Simple Notification Service （ SNS ）发送有关对对象执行的特定操作的通知。
+
例如，您可以配置向管理员发送有关添加到存储分段中的每个对象的警报，这些对象表示与关键系统事件关联的日志文件。

+

NOTE: 虽然可以在启用了 S3 对象锁定的存储分段上配置事件通知，但通知消息中不会包含对象的 S3 对象锁定元数据（包括保留至日期和合法保留状态）。

* * 搜索集成服务 * ： xref:understanding-search-integration-service.adoc[搜索集成服务] 用于将 S3 对象元数据发送到指定的 Elasticsearch 索引，在此索引中可以使用外部服务搜索或分析元数据。
+
例如，您可以将存储分段配置为将 S3 对象元数据发送到远程 Elasticsearch 服务。然后，您可以使用 Elasticsearch 跨存储分段执行搜索，并对对象元数据中存在的模式执行复杂的分析。

+

NOTE: 虽然可以在启用了 S3 对象锁定的情况下在存储分段上配置 Elasticsearch 集成，但通知消息中不会包含对象的 S3 对象锁定元数据（包括保留截止日期和合法保留状态）。



由于平台服务的目标位置通常不在 StorageGRID 部署中，因此平台服务可以为您提供使用外部存储资源，通知服务以及数据搜索或分析服务所带来的强大功能和灵活性。

可以为一个 S3 存储分段配置任何平台服务组合。例如，您可以在 StorageGRID S3 存储分段上配置 CloudMirror 服务和通知，以便将特定对象镜像到 Amazon Simple Storage Service ，同时向第三方监控应用程序发送有关每个此类对象的通知，以帮助您跟踪 AWS 支出。


IMPORTANT: StorageGRID 管理员必须使用网格管理器或网格管理 API 为每个租户帐户启用平台服务。



== 如何配置平台服务

平台服务与您使用租户管理器或租户管理 API 配置的外部端点进行通信。每个端点都代表一个外部目标，例如 StorageGRID S3 存储分段， Amazon Web 服务分段，简单通知服务（ SNS ）主题或本地托管， AWS 或其他位置的 Elasticsearch 集群。

创建端点后，您可以通过向存储分段添加 XML 配置来为存储分段启用平台服务。XML 配置可确定存储分段应处理的对象，存储分段应执行的操作以及存储分段应用于服务的端点。

您必须为要配置的每个平台服务添加单独的 XML 配置。例如：

. 如果要将密钥以 ` 或 images` 开头的所有对象复制到 Amazon S3 存储分段，则必须向源存储分段添加复制配置。
. 如果您还希望在这些对象存储到存储分段时发送通知，则必须添加通知配置。
. 最后，如果要为这些对象的元数据编制索引，则必须添加用于实施搜索集成的元数据通知配置。


配置 XML 的格式由用于实施 StorageGRID 平台服务的 S3 REST API 控制：

[cols="1a,2a"]
|===
| 平台服务 | S3 REST API 


 a| 
CloudMirror 复制
 a| 
* 获取存储分段复制
* PUT 存储分段复制




 a| 
通知
 a| 
* 获取存储分段通知
* PUT 存储分段通知




 a| 
搜索集成
 a| 
* 获取存储分段元数据通知配置
* PUT 存储分段元数据通知配置


这些操作是 StorageGRID 的自定义操作。

|===
有关 StorageGRID 如何实施这些 API 的详细信息，请参见有关实施 S3 客户端应用程序的说明。

.相关信息
xref:considerations-for-using-platform-services.adoc[使用平台服务的注意事项]

xref:../s3/index.adoc[使用 S3]
