---
permalink: vmware/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot installation issues 
summary: 如果在安装 StorageGRID 系统时出现任何问题，您可以访问安装日志文件。 
---
= 对安装问题进行故障排除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果在安装 StorageGRID 系统时出现任何问题，您可以访问安装日志文件。

以下是主要安装日志文件，技术支持可能需要这些文件来解决问题。

* ` /var/local/log/install.log` （可在所有网格节点上找到）
* ` /var/local/log/gdu-server.log` （位于主管理节点上）


要了解如何访问日志文件，请参见 xref:../monitor/index.adoc[StorageGRID 监控和故障排除说明]。有关排除设备安装问题的帮助，请参见适用于您的设备的安装和维护说明。如果您需要其他帮助，请联系技术支持。

xref:../sg100-1000/index.adoc[SG100 和 SG1000 服务设备]

xref:../sg6000/index.adoc[SG6000 存储设备]

xref:../sg5700/index.adoc[SG5700 存储设备]

xref:../sg5600/index.adoc[SG5600 存储设备]

https://mysupport.netapp.com/site/global/dashboard["NetApp 支持"^]



== 虚拟机资源预留需要调整

OVF 文件包含一个资源预留，用于确保每个网格节点都有足够的 RAM 和 CPU 来高效运行。如果通过在 VMware 上部署这些 OVF 文件来创建虚拟机，但预定义的资源数量不可用，则虚拟机将无法启动。

.关于此任务
如果您确定 VM 主机具有足够的资源来支持每个网格节点，请手动调整为每个虚拟机分配的资源，然后尝试启动虚拟机。

.步骤
. 在 VMware vSphere 虚拟机管理程序客户端树中，选择未启动的虚拟机。
. 右键‐单击虚拟机，然后选择 * 编辑设置 * 。
. 从虚拟机属性窗口中，选择 * 资源 * 选项卡。
. 调整分配给虚拟机的资源：
+
.. 选择 * CPU * ，然后使用预留滑块调整为此虚拟机预留的 MHz 。
.. 选择 * 内存 * ，然后使用预留滑块调整为此虚拟机预留的 MB 。


. 单击 * 确定 * 。
. 根据需要对同一 VM 主机上托管的其他虚拟机重复上述步骤。

