---
permalink: admin/configuring-client-connections.html 
sidebar: sidebar 
keywords: s3 connection, swift connection, connect to storagegrid 
summary: 作为网格管理员，您可以管理控制 S3 和 Swift 租户如何将客户端应用程序连接到 StorageGRID 系统以存储和检索数据的配置选项。有多种不同的选项可满足不同的客户端和租户要求。 
---
= 关于 S3 和 Swift 客户端连接
:icons: font
:imagesdir: ../media/


[role="lead"]
作为网格管理员，您可以管理控制 S3 和 Swift 租户如何将客户端应用程序连接到 StorageGRID 系统以存储和检索数据的配置选项。有多种不同的选项可满足不同的客户端和租户要求。

客户端应用程序可以通过连接到以下任一项来存储或检索对象：

* 管理节点或网关节点上的负载平衡器服务，或者也可以是管理节点或网关节点高可用性（ HA ）组的虚拟 IP 地址
* 网关节点上的 CLB 服务，或者也可以是网关节点高可用性组的虚拟 IP 地址
+

NOTE: CLB 服务已弃用。在 StorageGRID 11.3 版本之前配置的客户端可以继续在网关节点上使用 CLB 服务。所有其他依靠 StorageGRID 提供负载平衡的客户端应用程序都应使用负载平衡器服务进行连接。

* 存储节点，具有或不具有外部负载平衡器


您可以选择在 StorageGRID 系统上配置以下功能：

* * VLAN 接口 * ：您可以在管理节点和网关节点上创建虚拟 LAN （ VLAN ）接口，以隔离和分区客户端和租户流量，从而提高安全性，灵活性和性能。创建 VLAN 接口后，您可以将其添加到高可用性（ HA ）组中。
* * 高可用性组 * ：您可以为网关节点或管理节点的接口创建一个 HA 组来创建主动备份配置，也可以使用轮循 DNS 或第三方负载平衡器以及多个 HA 组来实现主动 - 主动配置。客户端连接使用 HA 组的虚拟 IP 地址进行。
* * 负载平衡器服务 * ：您可以通过为客户端连接创建负载平衡器端点来使客户端能够使用负载平衡器服务。创建负载平衡器端点时，您可以指定端口号，端点是否接受 HTTP 或 HTTPS 连接，将使用此端点的客户端类型（ S3 或 Swift ）以及用于 HTTPS 连接的证书（如果适用）。
* * 不可信客户端网络 * ：您可以通过将客户端网络配置为不可信来提高其安全性。如果客户端网络不可信，则客户端只能使用负载平衡器端点进行连接。


此外，您还可以为直接连接到存储节点或使用 CLB 服务（已弃用）连接到 StorageGRID 的客户端启用 HTTP ，并且可以为 S3 客户端配置 S3 API 端点域名。
