---
permalink: admin/how-load-balancing-works-load-balancer-service.html 
sidebar: sidebar 
keywords: load balancer service, how load balancing works 
summary: 负载平衡器服务将传入的网络连接从客户端应用程序分发到存储节点。要启用负载平衡，必须使用网格管理器配置负载平衡器端点。 
---
= 负载平衡的工作原理—负载平衡器服务
:icons: font
:imagesdir: ../media/


[role="lead"]
负载平衡器服务将传入的网络连接从客户端应用程序分发到存储节点。要启用负载平衡，必须使用网格管理器配置负载平衡器端点。

您只能为管理节点或网关节点配置负载平衡器端点，因为这些节点类型包含负载平衡器服务。您不能为存储节点或归档节点配置端点。

每个负载平衡器端点都指定一个端口，一个网络协议（ HTTP 或 HTTPS ），一个客户端类型（ S3 或 Swift ）和一个绑定模式。HTTPS 端点需要服务器证书。通过绑定模式，您可以将端点端口的可访问性限制为：

* 特定高可用性（ HA ）组的虚拟 IP 地址（ VIP ）
* 特定管理节点和网关节点的特定网络接口




== 端口注意事项

客户端可以访问您在运行负载平衡器服务的任何节点上配置的任何端点，但有两个例外：端口 80 和 443 在管理节点上保留，因此在这些端口上配置的端点仅支持网关节点上的负载平衡操作。

如果已重新映射任何端口，则不能使用相同的端口配置负载平衡器端点。您可以使用重新映射的端口创建端点，但这些端点将重新映射到原始 CLB 端口和服务，而不是负载平衡器服务。按照中的步骤进行操作 xref:../maintain/removing-port-remaps.adoc[删除端口重新映射]。


NOTE: CLB 服务已弃用。



== CPU 可用性

在向存储节点转发 S3 或 Swift 流量时，每个管理节点和网关节点上的负载平衡器服务会独立运行。通过加权过程，负载平衡器服务会将更多请求路由到 CPU 可用性更高的存储节点。节点 CPU 负载信息每隔几分钟更新一次，但权重可能会更频繁地更新。即使节点报告利用率为 100% 或未能报告利用率，也会为所有存储节点分配最小基本权重值。

在某些情况下，有关 CPU 可用性的信息仅限于负载平衡器服务所在的站点。
