---
permalink: admin/managing-traffic-classification-policies.html 
sidebar: sidebar 
keywords: qos, quality of service, traffic classification, best practices, limit traffic, monitor traffic 
summary: 要增强服务质量 \ （ QoS\ ）服务，您可以创建流量分类策略来识别和监控不同类型的网络流量。这些策略有助于限制和监控流量。 
---
= 管理流量分类策略
:icons: font
:imagesdir: ../media/


[role="lead"]
为了增强服务质量（ QoS ）服务，您可以创建流量分类策略来识别和监控不同类型的网络流量。这些策略有助于限制和监控流量。

流量分类策略应用于网关节点和管理节点的 StorageGRID 负载平衡器服务上的端点。要创建流量分类策略，必须已创建负载平衡器端点。



== 匹配规则和可选限制

每个流量分类策略都包含一个或多个匹配规则，用于标识与以下一个或多个实体相关的网络流量：

* 存储分段
* Tenants
* 子网（包含客户端的 IPv4 子网）
* 端点（负载平衡器端点）


StorageGRID 会根据规则的目标监控与策略中任何规则匹配的流量。与某个策略的任何规则匹配的任何流量均由该策略处理。相反，您可以设置规则来匹配除指定实体之外的所有流量。

您也可以根据以下参数为策略设置限制：

* 中的聚合带宽
* 聚合带宽不足
* 并发读取请求
* 并发写入请求
* 每个请求的带宽
* 每个请求的带宽不足
* 读取请求速率
* 写入请求速率



NOTE: 您可以创建策略来限制聚合带宽或限制每个请求的带宽。但是， StorageGRID 不能同时限制这两种类型的带宽。聚合带宽限制可能会对非受限流量产生额外的轻微性能影响。



== 流量限制

创建流量分类策略后，可以根据您设置的规则和限制类型来限制流量。对于聚合或每个请求的带宽限制，请求将以您设置的速率传入或移出。StorageGRID 只能强制执行一个速度，因此，按匹配器类型强制执行最具体的策略匹配。对于所有其他限制类型，客户端请求会延迟 250 毫秒，对于超过任何匹配策略限制的请求，客户端请求会收到 503 个响应速度较慢的响应。

在网格管理器中，您可以查看流量图表并验证策略是否正在强制实施预期的流量限制。



== 使用具有 SLA 的流量分类策略

您可以将流量分类策略与容量限制和数据保护结合使用来实施服务级别协议（ SLA ），这些协议提供了有关容量，数据保护和性能的具体信息。

每个负载平衡器都会实施流量分类限制。如果流量同时分布在多个负载平衡器上，则总最大速率是您指定的速率限制的倍数。

以下示例显示了一个 SLA 的三个层。您可以创建流量分类策略以实现每个 SLA 层的性能目标。

[cols="1a,1a,1a,1a,1a"]
|===
| 服务级别层 | Capacity | 数据保护 | 性能 | 成本 


 a| 
金牌
 a| 
允许 1 PB 存储
 a| 
3 复制 ILM 规则
 a| 
25 K 请求 / 秒

5 GB/ 秒（ 40 Gbps ）带宽
 a| 
每月 $$



 a| 
银牌
 a| 
允许使用 250 TB 存储
 a| 
2 复制 ILM 规则
 a| 
每秒 10 K 个请求

1.25 GB/ 秒（ 10 Gbps ）带宽
 a| 
每月 $$



 a| 
铜牌
 a| 
允许 100 TB 存储
 a| 
2 复制 ILM 规则
 a| 
5 K 请求 / 秒

1 GB/ 秒（ 8 Gbps ）带宽
 a| 
每月 $

|===