---
permalink: admin/manage-s3-select-for-tenant-accounts.html 
sidebar: sidebar 
keywords: s3 select, selectobjectcontent, best practices 
summary: 您可以允许某些 S3 租户对单个对象使用 S3 Select 到问题描述 SelectObjectContent 请求。 
---
= 管理租户帐户的 S3 Select
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以允许某些 S3 租户对单个对象使用 S3 Select 到问题描述 SelectObjectContent 请求。

S3 Select 可以高效地搜索大量数据，而无需部署数据库和相关资源即可启用搜索。它还可以降低检索数据的成本和延迟。



== 什么是 S3 Select ？

S3 Select 允许 S3 客户端使用 SelectObjectContent 请求仅筛选和检索对象所需的数据。S3 Select 的 StorageGRID 实施包括部分 S3 Select 命令和功能。



== 使用 S3 Select 的注意事项和要求

对于 S3 Select 查询， StorageGRID 需要满足以下要求：

* 要查询的对象为 CSV 格式，或者为包含 CSV 格式文件的 GZIP 或 bzip 2 压缩文件。
* 网格管理员必须授予租户 S3 Select 功能。选择 * 允许 S3 选择 * 时间 xref:creating-tenant-account.adoc[创建租户] 或 xref:editing-tenant-account.adoc[编辑租户]。
* SelectObjectContent 请求必须发送到 xref:configuring-load-balancer-endpoints.adoc[StorageGRID 负载平衡器端点]。端点使用的管理节点和网关节点必须是 SG100 或 SG1000 设备节点或基于 VMware 的软件节点。


请注意以下限制：

* 不支持裸机负载平衡器节点。
* 查询不能直接发送到存储节点。
* 不支持通过已弃用的 CLB 服务发送的查询。



IMPORTANT: SelectObjectContent 请求会降低所有 S3 客户端和所有租户的负载平衡器性能。仅在需要时才启用此功能，并且仅适用于受信任租户。

请参见 xref:../s3/use-s3-select.adoc[有关使用 S3 Select 的说明]。

以查看 xref:../monitor/reviewing-support-metrics.adoc[Grafana 图表] 对于随时间变化的 S3 Select 操作，请在网格管理器中选择 * 支持 * > * 工具 * > * 指标 * 。
