---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: 作为网格管理员，您可以创建和管理 S3 和 Swift 客户端用来存储和检索对象，监控存储使用情况以及管理客户端使用 StorageGRID 系统能够执行的操作的租户帐户。 
---
= 管理租户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
作为网格管理员，您可以创建和管理 S3 和 Swift 客户端用来存储和检索对象，监控存储使用情况以及管理客户端使用 StorageGRID 系统能够执行的操作的租户帐户。



== 什么是租户帐户？

租户帐户允许使用简单存储服务（ S3 ） REST API 或 Swift REST API 的客户端应用程序在 StorageGRID 上存储和检索对象。

每个租户帐户都支持使用一个协议，您可以在创建帐户时指定该协议。要将对象存储和检索到使用这两种协议的 StorageGRID 系统，您必须创建两个租户帐户：一个用于 S3 分段和对象，一个用于 Swift 容器和对象。每个租户帐户都有自己的帐户 ID ，授权组和用户，分段或容器以及对象。

或者，如果要将系统上存储的对象隔离为不同的实体，则可以创建其他租户帐户。例如，您可以在以下任一使用情形中设置多个租户帐户：

* * 企业用例： * 如果您在企业应用程序中管理 StorageGRID 系统，则可能需要按组织中的不同部门隔离网格的对象存储。在这种情况下，您可以为营销部门，客户支持部门，人力资源部门等创建租户帐户。
+

NOTE: 如果使用 S3 客户端协议，则只需使用 S3 分段和分段策略来隔离企业中各个部门之间的对象即可。您不需要使用租户帐户。有关详细信息，请参见实施 S3 客户端应用程序的说明。

* * 服务提供商用例： * 如果您将 StorageGRID 系统作为服务提供商进行管理，则可以按要在网格上租用存储的不同实体来隔离网格的对象存储。在这种情况下，您将为公司 A ，公司 B ，公司 C 等创建租户帐户。




== 创建和配置租户帐户

创建租户帐户时，您可以指定以下信息：

* 租户帐户的显示名称。
* 租户帐户（ S3 或 Swift ）将使用哪种客户端协议。
* 对于 S3 租户帐户：租户帐户是否有权对 S3 分段使用平台服务。如果您允许租户帐户使用平台服务，则必须确保已将网格配置为支持其使用。请 `M" 管理平台服务 " 。`
* （可选）租户帐户的存储配额—租户对象可用的最大 GB ， TB 或 PB 数。如果超过配额，租户将无法创建新对象。
+

NOTE: 租户的存储配额表示逻辑容量（对象大小），而不是物理容量（磁盘大小）。

* 如果为 StorageGRID 系统启用了身份联合，则哪个联合组具有 root 访问权限来配置租户帐户。
* 如果 StorageGRID 系统未使用单点登录（ SSO ），则表示租户帐户是使用自己的身份源还是共享网格的身份源，以及租户的本地 root 用户的初始密码。


创建租户帐户后，您可以执行以下任务：

* * 管理网格的平台服务 * ：如果您为租户帐户启用平台服务，请确保您了解如何传送平台服务消息以及使用平台服务对 StorageGRID 部署的网络要求。
* * 监控租户帐户的存储使用情况 * ：租户开始使用其帐户后，您可以使用 Grid Manager 监控每个租户占用的存储容量。
+

NOTE: 如果节点与网格中的其他节点隔离，则租户的存储使用量值可能会过时。恢复网络连接后，总数将更新。

+
如果已为租户设置配额，则可以启用 * 租户配额使用量高 * 警报以确定租户是否正在使用其配额。如果启用，则在租户已使用其配额的 90% 时触发此警报。有关详细信息，请参见 StorageGRID 监控和故障排除说明中的警报参考。

* * 配置客户端操作 * ：您可以配置是否禁止某些类型的客户端操作。




== 配置 S3 租户

创建 S3 租户帐户后，租户用户可以访问租户管理器以执行如下任务：

* 设置身份联合（除非身份源与网格共享）并创建本地组和用户
* 管理 S3 访问密钥
* 创建和管理 S3 存储分段
* 监控存储使用情况
* 使用平台服务（如果已启用）



IMPORTANT: S3 租户用户可以使用租户管理器创建和管理 S3 访问密钥和存储分段，但必须使用 S3 客户端应用程序载入和管理对象。



== 配置 Swift 租户

创建 Swift 租户帐户后，租户的 root 用户可以访问租户管理器以执行如下任务：

* 设置身份联合（除非身份源与网格共享），并创建本地组和用户
* 监控存储使用情况



IMPORTANT: Swift 用户必须具有 root 访问权限才能访问租户管理器。但是， " 根 " 访问权限不允许用户通过 Swift REST API 的身份验证来创建容器和载入对象。用户必须具有 Swift 管理员权限才能向 Swift REST API 进行身份验证。

xref:../tenant/index.adoc[使用租户帐户]
