---
permalink: admin/removing-user-or-group-from-cifs-audit-share.html 
sidebar: sidebar 
keywords: cifs audit client 
summary: 您不能删除允许访问审核共享的最后一个用户或组。 
---
= 从 CIFS 审核共享中删除用户或组
:icons: font
:imagesdir: ../media/


[role="lead"]
您不能删除允许访问审核共享的最后一个用户或组。

.您需要什么？ #8217 ；将需要什么
* 您已有 `passwords.txt` 文件以及根帐户密码（可在上述软件包中找到）。
* 您已有 `Configuration.txt` 文件（可在上述软件包中找到）。


已弃用通过 CIFS/Samba 进行审核导出，并将在未来的 StorageGRID 版本中删除。

.步骤
. 登录到主管理节点：
+
.. 输入以下命令： `ssh admin@ primary_Admin_Node_IP_`
.. 输入 `passwords.txt` 文件中列出的密码。
.. 输入以下命令切换到 root ： `su -`
.. 输入 `passwords.txt` 文件中列出的密码。
+
以 root 用户身份登录时，提示符将从 ` $` 更改为 ` #` 。



. 启动 CIFS 配置实用程序： `config_cifs.rb`
+
[listing]
----

---------------------------------------------------------------------
| Shares                 | Authentication         | Config          |
---------------------------------------------------------------------
| add-audit-share        | set-authentication     | validate-config |
| enable-disable-share   | set-netbios-name       | help            |
| add-user-to-share      | join-domain            | exit            |
| remove-user-from-share | add-password-server    |                 |
| modify-group           | remove-password-server |                 |
|                        | add-wins-server        |                 |
|                        | remove-wins-server     |                 |
---------------------------------------------------------------------
----
. 开始删除用户或组： `remove-user-from-share`
+
此时将显示一个编号列表，其中列出了管理节点的可用审核共享。审核共享标记为 audit-export 。

. 输入审核共享的编号： ` _audit_share_number_`
. 当系统提示删除用户或组时： `user` 或 `group`
+
此时将显示审核共享的用户或组的编号列表。

. 输入与要删除的用户或组对应的数字： ` _number_`
+
此时将更新审核共享，并且不再允许用户或组访问此审核共享。例如：

+
[listing]
----
Enabled shares
 1. audit-export
Select the share to change: 1
Remove user or group? [User/group]: User
Valid users for this share
1. audituser
2. newaudituser
Select the user to remove: 1

Removed user "audituser" from share "audit-export".

Press return to continue.
----
. 关闭 CIFS 配置实用程序： `exit`
. 如果 StorageGRID 部署包括其他站点的管理节点，请根据需要在每个站点禁用审核共享。
. 配置完成后，从每个命令 Shell 中注销： `exit`

