---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html 
sidebar: sidebar 
keywords: ip addresses for client, how to connect to storagegrid, ports, vip 
summary: 客户端应用程序可以使用网格节点的 IP 地址以及该节点上服务的端口号连接到 StorageGRID 。如果配置了高可用性组（ HA ），则客户端应用程序可以使用 HA 组的虚拟 IP 地址进行连接。 
---
= 摘要：客户端连接的 IP 地址和端口
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
客户端应用程序可以使用网格节点的 IP 地址以及该节点上服务的端口号连接到 StorageGRID 。如果配置了高可用性（ HA ）组，则客户端应用程序可以使用 HA 组的虚拟 IP 地址进行连接。

此表总结了客户端连接到 StorageGRID 的不同方式以及每种连接类型所使用的 IP 地址和端口。这些说明介绍了在已配置负载平衡器端点和高可用性（ HA ）组的情况下如何在网格管理器中查找此信息。

[cols="1a,1a,1a,1a"]
|===
| 建立连接的位置 | 客户端连接到的服务 | IP 地址 | Port 


 a| 
HA 组
 a| 
负载平衡器
 a| 
HA 组的虚拟 IP 地址
 a| 
* 负载平衡器端点端口




 a| 
HA 组
 a| 
CLB

* 注： * CLB 服务已弃用。
 a| 
HA 组的虚拟 IP 地址
 a| 
默认 S3 端口：

* HTTPS ： 8082
* HTTP ： 8084


默认 Swift 端口：

* HTTPS ： 8083
* HTTP ： 8085




 a| 
管理节点
 a| 
负载平衡器
 a| 
管理节点的 IP 地址
 a| 
* 负载平衡器端点端口




 a| 
网关节点
 a| 
负载平衡器
 a| 
网关节点的 IP 地址
 a| 
* 负载平衡器端点端口




 a| 
网关节点
 a| 
CLB

* 注： * CLB 服务已弃用。
 a| 
网关节点的 IP 地址

* 注意： * 默认情况下， CLB 和 LDR 的 HTTP 端口未启用。
 a| 
默认 S3 端口：

* HTTPS ： 8082
* HTTP ： 8084


默认 Swift 端口：

* HTTPS ： 8083
* HTTP ： 8085




 a| 
存储节点
 a| 
LDR
 a| 
存储节点的 IP 地址
 a| 
默认 S3 端口：

* HTTPS ： 18082
* HTTP ： 18084


默认 Swift 端口：

* HTTPS ： 18083
* HTTP ： 18085


|===
要将 S3 客户端连接到网关节点 HA 组的负载平衡器端点，请使用以下结构化 URL ：

* `https://_VIP-of-HA-group:LB-endpoint-port_`


例如，如果 HA 组的虚拟 IP 地址为 192.0.2.5 ，而 S3 负载平衡器端点的端口号为 10443 ，则 S3 客户端可以使用以下 URL 连接到 StorageGRID ：

* ` https://192.0.2.5:10443`


要将 Swift 客户端连接到网关节点 HA 组的负载平衡器端点，请使用以下结构化 URL ：

* `https://_VIP-of-HA-group:LB-endpoint-port_`


例如，如果 HA 组的虚拟 IP 地址为 192.0.2.6 ， Swift 负载平衡器端点的端口号为 10444 ，则 Swift 客户端可以使用以下 URL 连接到 StorageGRID ：

* ` https://192.0.2.6:10444`


可以为客户端用于连接到 StorageGRID 的 IP 地址配置 DNS 名称。请与本地网络管理员联系。

.步骤
. 使用登录到网格管理器 xref:../admin/web-browser-requirements.adoc[支持的 Web 浏览器]。
. 要查找网格节点的 IP 地址，请执行以下操作：
+
.. 选择 * 节点 * 。
.. 选择要连接到的管理节点，网关节点或存储节点。
.. 选择 * 概述 * 选项卡。
.. 在节点信息部分中，记下节点的 IP 地址。
.. 选择 * 显示更多 * 可查看 IPv6 地址和接口映射。
+
您可以建立从客户端应用程序到列表中任何 IP 地址的连接：

+
*** * eth0 ： * 网格网络
*** * eth1 ： * 管理网络（可选）
*** * eth2 ： * 客户端网络（可选）
+

NOTE: 如果您正在查看管理节点或网关节点，并且该节点是高可用性组中的活动节点，则 eth2 上会显示 HA 组的虚拟 IP 地址。





. 要查找高可用性组的虚拟 IP 地址，请执行以下操作：
+
.. 选择 * 配置 * > * 网络 * > * 高可用性组 * 。
.. 在表中，记下 HA 组的虚拟 IP 地址。


. 查找负载平衡器端点的端口号：
+
.. 选择 * 配置 * > * 网络 * > * 负载平衡器端点 * 。
+
此时将显示负载平衡器端点页面，其中显示了已配置的端点列表。

.. 选择一个端点，然后选择 * 编辑端点 * 。
+
此时将打开编辑端点窗口，并显示有关此端点的其他详细信息。

.. 确认已将选定端点配置为使用正确的协议（ S3 或 Swift ），然后选择 * 取消 * 。
.. 记下要用于客户端连接的端点的端点端口号。
+

NOTE: 如果端口号为 80 或 443 ，则仅在网关节点上配置端点，因为这些端口是在管理节点上保留的。所有其他端口都在网关节点和管理节点上进行配置。




