---
permalink: s3/changes-to-s3-rest-api-support.html 
sidebar: sidebar 
keywords: s3 rest api support changes 
summary: 您应了解 StorageGRID 系统对 S3 REST API 的支持发生了哪些变化。 
---
= 对 S3 REST API 支持的更改
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应了解 StorageGRID 系统对 S3 REST API 的支持发生了哪些变化。

[cols="1a,4a"]
|===
| 版本。 | 注释 


 a| 
11.6.
 a| 
* 增加了对在 GET 对象和 HEAD 对象请求中使用 `partnumber` request 参数的支持。
* 增加了对 S3 对象锁定的默认保留模式和存储分段级别的默认保留期限的支持。
* 增加了对 `s 3 ： object-lock-real-retention-days` 策略条件密钥的支持，用于设置对象允许的保留期限范围。
* 现在，单个 PUT 对象操作的最大 _recommended_size 为 5 GiB （ 5 ， 368 ， 709 ， 120 字节）。如果对象大于 5 GiB ，请改用多部分上传。



IMPORTANT: 在 StorageGRID 11.6 中，单个 PUT 对象操作的最大 _supported _ 大小仍为 5 TiB （ 5 ， 497 ， 552 ， 138 ， 880 字节）。但是，如果您尝试上传超过 5 GiB 的对象，则会触发 * S3 PUT Object Size Too large* 警报。



 a| 
11.5
 a| 
* 增加了对管理存储分段加密的支持。
* 增加了对 S3 对象锁定和已弃用旧合规性请求的支持。
* 增加了对在版本控制的存储分段上使用删除多个对象的支持。
* 现在可以正确支持 `Content-MD5` 请求标头。




 a| 
11.4
 a| 
* 增加了对删除存储分段标记，获取存储分段标记和放置存储分段标记的支持。不支持成本分配标记。
* 对于在 StorageGRID 11.4 中创建的分段，不再需要限制对象密钥名称以满足性能最佳实践。
* 增加了对 `s 3 ： ObjectRestore ： POST` 事件类型的存储分段通知的支持。
* 现在，多部件的 AWS 大小限制已强制实施。多部分上传中的每个部件必须介于 5 MiB 和 5 GiB 之间。最后一个部件可以小于 5 MiB 。
* 增加了对 TLS 1.3 的支持，并更新了支持的 TLS 密码套件列表。
* CLB 服务已弃用。




 a| 
11.3
 a| 
* 增加了对使用客户提供的密钥（ SSI-C ）对对象数据进行服务器端加密的支持。
* 增加了对删除，获取和放置分段生命周期操作（仅限到期操作）以及 `x-AMZ-expiration` 响应标头的支持。
* 更新了 PUT 对象， PUT 对象 - 复制和多部件上传，以说明在载入时使用同步放置的 ILM 规则的影响。
* 更新了支持的 TLS 密码套件列表。不再支持 TLS 1.1 密码。




 a| 
11.2.
 a| 
增加了对用于云存储池的后对象还原的支持。增加了对在组和存储分段策略中使用 AWS 语法来处理 ARN ，策略条件密钥和策略变量的支持。仍支持使用 StorageGRID 语法的现有组和存储分段策略。

* 注意： * 在其他配置 JSON/XML 中使用 ARN/URN 的情况没有改变，包括在自定义 StorageGRID 功能中使用的情况。



 a| 
11.1
 a| 
增加了对跨源资源共享（ CORS ）， S3 客户端到网格节点连接的 HTTP 以及存储分段上的合规性设置的支持。



 a| 
11.0
 a| 
增加了对为存储分段配置平台服务（ CloudMirror 复制，通知和 Elasticsearch 搜索集成）的支持。此外，还增加了对存储分段的对象标记位置约束以及可用一致性控制设置的支持。



 a| 
10.4.
 a| 
增加了对版本控制，端点域名页面更新，策略中的条件和变量，策略示例以及 PutOverwriteObject 权限的 ILM 扫描更改的支持。



 a| 
10.3
 a| 
增加了对版本控制的支持。



 a| 
10.2
 a| 
增加了对组和存储分段访问策略以及多部件副本（上传部件 - 复制）的支持。



 a| 
10.1
 a| 
增加了对多部分上传，虚拟托管模式请求和 v4 身份验证的支持。



 a| 
10.0
 a| 
StorageGRID 系统最初支持 S3 REST API 。当前支持的 _Simple Storage Service API 参考版本为 2006-03-01 。

|===