---
permalink: s3/head-object.html 
sidebar: sidebar 
keywords: head object 
summary: 您可以使用 S3 head Object 请求从对象检索元数据，而无需返回对象本身。 
---
= HEAD 对象
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 S3 head Object 请求从对象检索元数据，而无需返回对象本身。如果对象存储在云存储池中，则可以使用 head 对象确定对象的过渡状态。



== head 对象和多部分对象

您可以使用 `partnumber` request 参数检索多部分或已分段对象的特定部分的元数据。`x-AMZ-MP-parts-count` 响应元素指示对象包含的部件数。

对于已分段 / 多部分对象和未分段 / 非多部分对象，您可以将 `partnumber` 设置为 1 ；但是，仅对于已分段或多部分对象，才会返回 `x-AMZ-MP-parts-count` response 元素。



== 使用客户提供的加密密钥（ SSI-C ）进行服务器端加密的请求标头

如果对象使用您提供的唯一密钥进行加密，请使用所有这三个标头。

* `x-AMZ-server-side encrypt-customer-all` ：指定 `AES256` 。
* `x-AMZ-server-side encrypt-customer-key` ：指定对象的加密密钥。
* `x-AMZ-server-side encrypt-customer-key-md5` ：指定对象加密密钥的 MD5 摘要。



IMPORTANT: 您提供的加密密钥永远不会存储。如果丢失加密密钥，则会丢失相应的对象。在使用客户提供的密钥保护对象数据之前，请查看 "`使用服务器端加密 " 中的注意事项。`



== 用户元数据中的 UTF-8 字符

StorageGRID 不会解析或解释用户定义的元数据中的转义 UTF-8 字符。如果密钥名称或值包含不可打印的字符，则对用户定义的元数据中包含转义 UTF-8 字符的对象发出的 HEAD 请求不会返回 `x-AMZ-MISSING-meta` 标头。



== 请求标头不受支持

不支持以下请求标头，并返回 `XNotImplemented"` ：

* `x-AMZ-website-redirect-location`




== Cloud Storage Pool 对象的响应标头

如果对象存储在云存储池中（请参见有关通过信息生命周期管理来管理对象的说明），则返回以下响应标头：

* `X-AMZ-storage-class ： Glacier`
* `x-AMZ-restore`


响应标头提供了有关对象移动到云存储池，可选择过渡到不可检索状态并已还原时的状态的信息。

|===
| 对象的状态 | 对 head 对象的响应 


 a| 
对象已载入 StorageGRID 但尚未通过 ILM 进行评估，或者存储在传统存储池中的对象或使用纠删编码
 a| 
`200 正常` （不返回任何特殊响应标头。）



 a| 
云存储池中的对象，但尚未过渡到无法检索的状态
 a| 
`200 正常`

`X-AMZ-storage-class ： Glacier`

`x-AMZ-restore ： ongoing-request="false" ， expiry-date="Sat" ， 20 年 7 月 23 日 203000000000000000000000"`

在将对象过渡到不可检索的状态之前， `expiry-date` 的值将设置为未来的某个远程时间。确切的过渡时间不受 StorageGRID 系统控制。



 a| 
对象已过渡到不可检索状态，但网格上至少也存在一个副本
 a| 
`200 正常`

`X-AMZ-storage-class ： Glacier`

`x-AMZ-restore ： ongoing-request="false" ， expiry-date="Sat" ， 20 年 7 月 23 日 203000000000000000000000"`

`expiry-date` 的值将设置为未来的某个距离时间。

* 注意 * ：如果网格上的副本不可用（例如，存储节点已关闭），则必须先对后对象还原请求进行问题描述 处理，以便从云存储池还原此副本，然后才能成功检索此对象。



 a| 
对象已过渡到无法检索的状态，网格上不存在任何副本
 a| 
`200 正常`

`X-AMZ-storage-class ： Glacier`



 a| 
正在从不可检索状态还原的对象
 a| 
`200 正常`

`X-AMZ-storage-class ： Glacier`

`x-AMZ-restore ： ongoing-request="true"`



 a| 
对象已完全还原到云存储池
 a| 
`200 正常`

`X-AMZ-storage-class ： Glacier`

`x-AMZ-restore ： ongoing-request="false" ， expiry-date="Sat" ， 2018 年 7 月 23 日 00 ： 00 ： 00 GMT"`

`expiry-date` 指示何时将云存储池中的对象返回到不可检索的状态。

|===


== 云存储池中的多部分或分段对象

如果您上传的是多部分对象或 StorageGRID 将一个大型对象拆分为多个区块，则 StorageGRID 会通过取样该对象的部分或区块来确定该对象是否在云存储池中可用。在某些情况下，如果对象的某些部分已过渡到不可检索的状态或对象的某些部分尚未还原，则 HEAD 对象请求可能会错误地返回 `x-AMZ-restore ： ongoing-request="false"` 。



== 版本控制

如果未指定 `veversionId` Subresource ，则此操作将提取受版本控制的存储分段中的对象的最新版本。如果对象的当前版本为删除标记，则返回 "`not found` " 状态，并将 `x-AMZ-delete-marker` response 标头设置为 `true` 。

xref:using-server-side-encryption.adoc[使用服务器端加密]

xref:../ilm/index.adoc[使用 ILM 管理对象]

xref:post-object-restore.adoc[后对象还原]

xref:s3-operations-tracked-in-audit-logs.adoc[在审核日志中跟踪 S3 操作]
