---
permalink: s3/s3-rest-api-supported-operations-and-limitations.html 
sidebar: sidebar 
keywords: s3 rest api supported operations, s3 rest api limitations 
summary: StorageGRID 系统实施简单存储服务 API （ API 版本 2006-03-01 ），支持大多数操作，但有一些限制。在集成 S3 REST API 客户端应用程序时，您需要了解实施详细信息。 
---
= S3 REST API 支持的操作和限制
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 系统实施简单存储服务 API （ API 版本 2006-03-01 ），支持大多数操作，但有一些限制。在集成 S3 REST API 客户端应用程序时，您需要了解实施详细信息。

StorageGRID 系统既支持虚拟托管模式请求，也支持路径模式请求。



== 日期处理

S3 REST API 的 StorageGRID 实施仅支持有效的 HTTP 日期格式。

对于接受日期值的任何标头， StorageGRID 系统仅支持有效的 HTTP 日期格式。日期的时间部分可以使用格林威治标准时间（ GMT ）格式或通用协调时间（ UTC ）格式指定，并且不存在时区偏移（必须指定 +0000 ）。如果您在请求中包含 `x-AMZ-date` 标题，则此标题将覆盖日期请求标题中指定的任何值。使用 AWS 签名版本 4 时，签名请求中必须包含 `x-AMZ-date` 标头，因为不支持日期标头。



== 通用请求标头

StorageGRID 系统支持由定义的通用请求标头 http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html["Amazon Web Services （ AWS ）文档： Amazon Simple Storage Service API 参考"^]，但有一个例外。

|===
| 请求标题 | 实施 


 a| 
Authorization
 a| 
完全支持 AWS 签名版本 2

支持 AWS 签名版本 4 ，但以下情况除外：

* 不会为请求正文计算 SHA256 值。接受用户提交的值而不进行验证，就好像为 `x-AMZ-content-SHA256` 标头提供了值 `unsigned-load` 一样。




 a| 
X-AMZ-securation-token
 a| 
未实施。返回 `XNotImplemented"` 。

|===


== 通用响应标头

StorageGRID 系统支持由 _Simple Storage Service API 参考 _ 定义的所有通用响应标头，但有一个例外。

|===
| 响应标头 | 实施 


 a| 
X-AMZ-ID-2
 a| 
未使用

|===