---
permalink: s3/storagegrid-s3-rest-api-operations.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations 
summary: S3 REST API 中添加了特定于 StorageGRID 系统的操作。 
---
= StorageGRID S3 REST API 操作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 REST API 中添加了特定于 StorageGRID 系统的操作。

* xref:../s3/get-bucket-consistency-request.adoc[获取存储分段一致性请求]
+
使用获取存储分段一致性请求，您可以确定应用于特定存储分段的一致性级别。

* xref:../s3/put-bucket-consistency-request.adoc[PUT 存储分段一致性请求]
+
通过 PUT 分段一致性请求，您可以指定要应用于对分段执行的操作的一致性级别。

* xref:../s3/get-bucket-last-access-time-request.adoc[获取分段上次访问时间请求]
+
通过获取分段上次访问时间请求，您可以确定是为单个分段启用还是禁用了上次访问时间更新。

* xref:../s3/put-bucket-last-access-time-request.adoc[PUT 分段上次访问时间请求]
+
通过 PUT 分段上次访问时间请求，您可以为各个分段启用或禁用上次访问时间更新。禁用上次访问时间更新可提高性能，它是使用 10.3.0 或更高版本创建的所有存储分段的默认设置。

* xref:../s3/delete-bucket-metadata-notification-configuration-request.adoc[删除存储分段元数据通知配置请求]
+
通过删除存储分段元数据通知配置请求，您可以通过删除配置 XML 来禁用各个存储分段的搜索集成服务。

* xref:../s3/get-bucket-metadata-notification-configuration-request.adoc[获取存储分段元数据通知配置请求]
+
使用获取分段元数据通知配置请求，您可以检索用于为各个分段配置搜索集成的配置 XML 。

* xref:../s3/put-bucket-metadata-notification-configuration-request.adoc[PUT 存储分段元数据通知配置请求]
+
通过 PUT Bucket 元数据通知配置请求，您可以为各个存储分段启用搜索集成服务。您在请求正文中提供的元数据通知配置 XML 用于指定将其元数据发送到目标搜索索引的对象。

* xref:../s3/get-storage-usage-request.adoc[获取存储使用情况请求]
+
" 获取存储使用量 " 请求会告知您帐户正在使用的存储总量以及与帐户关联的每个存储分段的存储总量。

* xref:../s3/deprecated-bucket-requests-for-legacy-compliance.adoc[已弃用旧合规性的存储分段请求]
+
您可能需要使用 StorageGRID S3 REST API 来管理使用原有合规性功能创建的分段。


