---
permalink: monitor/set-up-snmp-alert-notifications.html 
sidebar: sidebar 
keywords: how to use snmp notifications for alerts 
summary: 如果您希望 StorageGRID 在发生警报时发送 SNMP 通知，则必须启用 StorageGRID SNMP 代理并配置一个或多个陷阱目标。 
---
= 为警报设置 SNMP 通知
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您希望 StorageGRID 在发生警报时发送 SNMP 通知，则必须启用 StorageGRID SNMP 代理并配置一个或多个陷阱目标。

您可以使用网格管理器中的 * 配置 * > * 监控 * > * SNMP 代理 * 选项或网格管理 API 的 SNMP 端点来启用和配置 StorageGRID SNMP 代理。SNMP 代理支持所有三个版本的 SNMP 协议。

要了解如何配置 SNMP 代理，请参见 xref:using-snmp-monitoring.adoc[使用 SNMP 监控]。

配置 StorageGRID SNMP 代理后，可以发送两种类型的事件驱动型通知：

* 陷阱是指 SNMP 代理发送的通知，不需要管理系统确认。陷阱用于通知管理系统 StorageGRID 中发生了某种情况，例如触发警报。所有三个版本的 SNMP 均支持陷阱。
* 通知与陷阱类似，但需要管理系统确认。如果 SNMP 代理未在特定时间内收到确认，则会重新发送通知，直到收到确认或达到最大重试值为止。SNMPv2c 和 SNMPv3 支持 INFORM 。


在任何严重性级别触发默认或自定义警报时，系统都会发送陷阱和通知通知通知。要禁止警报的 SNMP 通知，您必须为此警报配置静默。请参见 xref:silencing-alert-notifications.adoc[静默警报通知]。

警报通知由配置为首选发送方的任何管理节点发送。默认情况下，会选择主管理节点。请参见 xref:../admin/index.adoc[有关管理 StorageGRID 的说明]。


NOTE: 在指定严重性级别或更高级别触发某些警报（传统系统）时，也会发送陷阱和通知通知通知；但是，不会针对每个警报或每个警报严重性发送 SNMP 通知。请参见 xref:alarms-that-generate-snmp-notifications.adoc[生成 SNMP 通知的警报（旧系统）]。
