---
permalink: monitor/using-snmp-monitoring.html 
sidebar: sidebar 
keywords: snmp, monitoring 
summary: 如果要使用简单网络管理协议（ SNMP\ ）监控 StorageGRID ，则必须配置 StorageGRID 附带的 SNMP 代理。 
---
= 使用 SNMP 监控
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要使用简单网络管理协议（ Simple Network Management Protocol ， SNMP ）监控 StorageGRID ，则必须配置 StorageGRID 附带的 SNMP 代理。

* xref:configuring-snmp-agent.adoc[配置 SNMP 代理]
* xref:updating-snmp-agent.adoc[更新 SNMP 代理]




== 功能

每个 StorageGRID 节点都运行一个 SNMP 代理或守护进程，该代理或守护进程可提供一个管理信息库（ Management Information Base ， MIB ）。StorageGRID MIB 包含警报和警报的表和通知定义。MIB 还包含系统问题描述 信息，例如每个节点的平台和型号。每个 StorageGRID 节点还支持一组 MIB-II 对象。

最初，所有节点上都会禁用 SNMP 。配置 SNMP 代理时，所有 StorageGRID 节点都会收到相同的配置。

StorageGRID SNMP 代理支持所有三个版本的 SNMP 协议。它为查询提供只读 MIB 访问权限，并可向管理系统发送两种类型的事件驱动型通知：

* * 陷阱 * 是 SNMP 代理发送的通知，不需要管理系统确认。陷阱用于通知管理系统 StorageGRID 中发生了某种情况，例如触发警报。
+
所有三个版本的 SNMP 均支持陷阱。

* * 通知 * 与陷阱类似，但它们需要管理系统确认。如果 SNMP 代理未在特定时间内收到确认，则会重新发送通知，直到收到确认或达到最大重试值为止。
+
SNMPv2c 和 SNMPv3 支持 INFORM 。



在以下情况下会发送陷阱和通知通知通知：

* 默认或自定义警报将在任何严重性级别触发。要禁止警报的 SNMP 通知，您必须为此警报配置静默。警报通知由配置为首选发送方的任何管理节点发送。
+
每个警报都会根据警报的严重性级别映射到以下三种陷阱类型之一： activeMinorAlert ， activeMajorAlert 和 activeCriticalAlert 。有关可能触发这些陷阱的警报的说明，请参见 xref:alerts-reference.adoc[警报参考]。

* 某些警报（旧系统）会在指定的严重性级别或更高级别触发。
+

NOTE: 不会针对每个警报或每个警报严重性发送 SNMP 通知。





== SNMP 版本支持

下表简要总结了每个 SNMP 版本支持的功能。

|===
|  | SNMPv1 | SNMPv2c | SNMPv3 


 a| 
查询
 a| 
只读 MIB 查询
 a| 
只读 MIB 查询
 a| 
只读 MIB 查询



 a| 
查询身份验证
 a| 
社区字符串
 a| 
社区字符串
 a| 
基于用户的安全模型（ USM ）用户



 a| 
通知
 a| 
仅陷阱
 a| 
陷阱和通知
 a| 
陷阱和通知



 a| 
通知身份验证
 a| 
每个陷阱目标的默认陷阱社区或自定义社区字符串
 a| 
每个陷阱目标的默认陷阱社区或自定义社区字符串
 a| 
每个陷阱目标的 USM 用户

|===


== 限制

* StorageGRID 支持只读 MIB 访问。不支持读写访问。
* 网格中的所有节点都接收相同的配置。
* SNMPv3 ： StorageGRID 不支持传输支持模式（ TSM ）。
* SNMPv3 ：支持的唯一身份验证协议是 SHA （ HMAC-SHA-96 ）。
* SNMPv3 ：支持的唯一隐私协议是 AES 。




== 访问 MIB

您可以在任何 StorageGRID 节点上的以下位置访问 MIB 定义文件：

` /usr/share/snmp/MIBS/NetApp-STORAGEGRID-MIB.txt`

.相关信息
* xref:alerts-reference.adoc[警报参考]
* xref:alarms-reference.adoc[警报参考（旧系统）]
* xref:alarms-that-generate-snmp-notifications.adoc[生成 SNMP 通知的警报（旧系统）]
* xref:silencing-alert-notifications.adoc[静默警报通知]

