---
permalink: maintain/configuring-ntp-servers.html 
sidebar: sidebar 
keywords: storagegrid, ntp, ntp server, configure ntp, configuring ntp 
summary: 您可以添加，更新或删除网络时间协议（ NTP ）服务器，以确保 StorageGRID 系统中的网格节点之间数据准确同步。 
---
= 配置 NTP 服务器
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以添加，更新或删除网络时间协议（ Network Time Protocol ， NTP ）服务器，以确保 StorageGRID 系统中的网格节点之间准确同步数据。

.您需要什么？ #8217 ；将需要什么
* 您必须使用登录到网格管理器 xref:../admin/web-browser-requirements.adoc[支持的 Web 浏览器]。
* 您必须具有维护或根访问权限。
* 您必须具有配置密码短语。
* 您必须具有要配置的 NTP 服务器的 IPv4 地址。


StorageGRID 系统使用网络时间协议（ NTP ）来同步网格中所有网格节点之间的时间。

在每个站点上，至少会为 StorageGRID 系统中的两个节点分配主 NTP 角色。它们会同步到建议的至少四个外部时间源，最多六个外部时间源以及彼此之间。StorageGRID 系统中不是主 NTP 节点的每个节点都充当 NTP 客户端，并与这些主 NTP 节点同步。

外部 NTP 服务器连接到先前已为其分配主 NTP 角色的节点。因此，建议至少指定两个具有主 NTP 角色的节点。


IMPORTANT: 确保每个站点至少有两个节点可以访问至少四个外部 NTP 源。如果一个站点上只有一个节点可以访问 NTP 源，则在该节点关闭时会发生计时问题。此外，指定每个站点两个节点作为主要 NTP 源可确保在站点与网格其余部分隔离时的时间准确无误。

指定的外部 NTP 服务器必须使用 NTP 协议。您必须指定 Stratum 3 或更高的 NTP 服务器引用，以防止出现时间偏差问题。


NOTE: 在为生产级 StorageGRID 安装指定外部 NTP 源时，请勿在 Windows Server 2016 之前的 Windows 版本上使用 Windows 时间（ W32Time ）服务。早期版本的 Windows 上的时间服务不够准确， Microsoft 不支持在 StorageGRID 等高精度环境中使用。

https://support.microsoft.com/en-us/help/939322/support-boundary-to-configure-the-windows-time-service-for-high-accura["支持边界，用于为高精度环境配置 Windows 时间服务"^]

如果您遇到安装期间最初指定的 NTP 服务器的稳定性或可用性问题，可以通过添加其他服务器或更新或删除现有服务器来更新 StorageGRID 系统使用的外部 NTP 源列表。

.步骤
. 选择 * 维护 * > * 网络 * > * NTP 服务器 * 。
. 在服务器部分中，根据需要添加更新或删除 NTP 服务器条目。
+
您应至少包含 4 个 NTP 服务器，并且最多可以指定 6 个服务器。

. 在 * 配置密码短语 * 文本框中，输入 StorageGRID 系统的配置密码短语，然后单击 * 保存 * 。
+
操作步骤 的状态显示在页面顶部。在配置更新完成之前，此页面将处于禁用状态。

+

IMPORTANT: 如果在保存新 NTP 服务器后所有 NTP 服务器均未通过连接测试，请勿继续。请联系技术支持。


