---
permalink: maintain/copying-audit-logs-from-failed-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, audit log, copy audit log, copying audit log, primary admin node, primary admin node 
summary: 如果您能够从出现故障的主管理节点复制审核日志，则应保留这些日志以维护网格中的系统活动和使用情况记录。您可以在恢复的主管理节点启动并运行后将保留的审核日志还原到该节点。 
---
= 从发生故障的主管理节点复制审核日志
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您能够从出现故障的主管理节点复制审核日志，则应保留这些日志以维护网格中的系统活动和使用情况记录。您可以在恢复的主管理节点启动并运行后将保留的审核日志还原到该节点。

此操作步骤 会将审核日志文件从故障管理节点复制到单独网格节点上的临时位置。然后，可以将这些保留的审核日志复制到替代管理节点。审核日志不会自动复制到新的管理节点。

根据故障类型，您可能无法从发生故障的管理节点复制审核日志。如果部署只有一个管理节点，则恢复的管理节点将开始在新的空文件中将事件记录到审核日志中，并且先前记录的数据将丢失。如果部署包含多个管理节点，则可以从另一个管理节点恢复审核日志。


NOTE: 如果现在无法在出现故障的管理节点上访问审核日志，您可以稍后访问这些日志，例如在主机恢复之后。

. 如果可能，请登录到出现故障的管理节点。否则，请登录到主管理节点或其他管理节点（如果有）。
+
.. 输入以下命令： `ssh admin@ grid_node_ip_`
.. 输入 `passwords.txt` 文件中列出的密码。
.. 输入以下命令切换到 root ： `su -`
.. 输入 `passwords.txt` 文件中列出的密码。
+
以 root 用户身份登录时，提示符将从 ` $` 更改为 ` #` 。



. 停止 AMS 服务以防止其创建新的日志文件：``sservice AMS stop``
. 重命名 audit.log 文件，使其在复制到已恢复的管理节点时不会覆盖现有文件。
+
将 audit.log 重命名为唯一编号的文件名，例如 yyyy-mm-dd.txt.1 。例如，您可以将 audit.log 文件重命名为 2015-10-25.txt 。 1``cd /var/local/audit/export```ls -l``mv audit.log 2015-10-25.1`

. 重新启动 AMS 服务： `sservice AMS start`
. 创建目录以将所有审核日志文件复制到单独网格节点上的临时位置： `ssh admin@ grid_node_ip_ mkdir -p /var/local/tmp/saved-audit-logs`
+
出现提示时，输入 admin 的密码。

. 复制所有审核日志文件： `scp -p * admin@ grid_node_ip_ ： /var/local/tmp/saved-audit-logs`
+
出现提示时，输入 admin 的密码。

. 以 root 用户身份注销： `exit`

