---
permalink: maintain/gathering-required-materials-for-grid-node-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recovery, grid node recovery, node recovery 
summary: 在执行维护过程之前，您必须确保具有必要的材料来恢复出现故障的网格节点。 
---
= 收集网格节点恢复所需的材料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在执行维护过程之前，您必须确保具有必要的材料来恢复出现故障的网格节点。

[cols="1a,2a"]
|===
| 项目 | 注释： 


 a| 
StorageGRID 安装归档
 a| 
如果需要恢复网格节点，则需要 <<download-and-extract-install-files-recover,下载 StorageGRID 安装文件>> 适用于您的平台。

* 注意： * 如果要恢复存储节点上的故障存储卷，则不需要下载文件。



 a| 
服务笔记本电脑
 a| 
服务笔记本电脑必须具有以下组件：

* 网络端口
* SSH 客户端（例如 PuTTY ）
* xref:../admin/web-browser-requirements.adoc[支持的 Web 浏览器]




 a| 
恢复软件包 ` .zip` 文件
 a| 
获取最新恢复软件包 ` .zip` 文件的副本： `sGWS-recovery-package-_id-revision_.zip`

每次修改系统时，都会更新 ` .zip` 文件的内容。在进行此类更改后，系统会指示您将最新版本的恢复软件包存储在安全位置。使用最新副本从网格故障中恢复。

如果主管理节点运行正常，您可以从网格管理器下载恢复软件包。选择 * 维护 * > * 系统 * > * 恢复软件包 * 。

如果您无法访问网格管理器，则可以在包含此 ADC 服务的某些存储节点上找到恢复软件包的加密副本。在每个存储节点上，检查恢复软件包的位置： ` /var/local/install/sgws-recovery-package-_grid_-_revision_.zip 。 gpg` 使用修订版号最高的恢复软件包。



 a| 
`passwords.txt` file
 a| 
包含访问命令行上的网格节点所需的密码。包含在恢复包中。



 a| 
配置密码短语
 a| 
首次安装 StorageGRID 系统时，系统会创建并记录密码短语。配置密码短语不在 `passwords.txt` 文件中。



 a| 
适用于您的平台的最新文档
 a| 
请访问平台供应商的网站以获取相关文档。

有关您的平台当前支持的版本，请参见 https://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^]。

|===


== 下载并提取 StorageGRID 安装文件

下载软件并提取文件，除非您这样做 xref:recovering-from-storage-node-failures.adoc[恢复存储节点上的故障存储卷]。

您必须使用网格上当前运行的 StorageGRID 版本。

.步骤
. 确定当前安装的软件版本。从网格管理器顶部，选择帮助图标并选择 * 关于 * 。
. 转至 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["StorageGRID 的 "NetApp 下载 " 页面"]。
. 选择网格上当前运行的 StorageGRID 版本。
+
StorageGRID 软件版本采用以下格式： `11.x.y` 。

. 使用您的 NetApp 帐户的用户名和密码登录。
. 阅读最终用户许可协议，选中复选框，然后选择 * 接受并继续 * 。
. 在下载页面的 * 安装 StorageGRID * 列中，为您的平台选择 ` .tgz` 或 ` .zip` 文件。
+
安装归档文件中显示的版本必须与当前安装的软件版本匹配。

+
如果您运行的是 Windows ，请使用 ` .zip` 文件。

+
[cols="1a,2a"]
|===
| 平台 | 安装归档 


 a| 
Red Hat Enterprise Linux 或 CentOS
| `storageGRID-Webscale -_version_-RPM-_uniqueID_.zip` `StorageGRID-Webscale -_version_-RPM-_uniqueID_.tgz` 


 a| 
Ubuntu ， Debian 或设备
| `storageGRID-Webscale -_version_-Deb-uniqueID_.zip` `StorageGRID-Webscale -_version_-Deb-uniqueID_.tgz` 


 a| 
VMware
| `storageGRID-Webscale -_version_-vmware-_uniqueID_.zip` `StorageGRID-Webscale -_version_-vmware-_uniqueID_.tgz` 
|===
. 下载并提取归档文件。
. 根据您的平台以及需要恢复的网格节点，按照适用于您的平台的步骤选择所需的文件。
+
步骤中为每个平台列出的路径与归档文件安装的顶级目录相对。

. 如果要恢复 xref:../rhel/index.adoc[Red Hat Enterprise Linux 或 CentOS 系统]下，选择相应的文件。


[cols="1a,1a"]
|===
| 路径和文件名 | Description 


| ./rpms/README  a| 
一个文本文件，用于描述 StorageGRID 下载文件中包含的所有文件。



| ./rpms/NLF000000.txt  a| 
一种免费许可证，不提供产品的任何支持授权。



| ./rpms/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
RPM 软件包，用于在 RHEL 或 CentOS 主机上安装 StorageGRID 节点映像。



| ./rpms/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
RPM 软件包，用于在 RHEL 或 CentOS 主机上安装 StorageGRID 主机服务。



| 部署脚本工具 | Description 


| ./rpms/configure-storagegrid.py  a| 
一种用于自动配置 StorageGRID 系统的 Python 脚本。



| ./rpms/configure-sga.py  a| 
一种用于自动配置 StorageGRID 设备的 Python 脚本。



| ./rpms/configure-storagegrid.sample.json  a| 
与 `configure-storaggrid.py` 脚本结合使用的示例配置文件。



| ./rpms/storagegrid-ssoauth.py  a| 
一个示例 Python 脚本，启用单点登录后，您可以使用该脚本登录到网格管理 API 。



| ./rpms/configure-storagegrid.blank.json  a| 
用于 `configure-storaggrid.py` 脚本的空配置文件。



| ./rpms/Extras 或 Ansible  a| 
用于为 StorageGRID 容器部署配置 RHEL 或 CentOS 主机的 Ansible 角色示例和攻略手册。您可以根据需要自定义角色或攻略手册。



| ./rpms/Extras 或 API 架构  a| 
StorageGRID 的 API 架构。

* 注意 * ：在执行升级之前，如果您没有用于升级兼容性测试的非生产 StorageGRID 环境，则可以使用这些架构确认为使用 StorageGRID 管理 API 编写的任何代码都与新的 StorageGRID 版本兼容。

|===
. 如果要恢复 xref:../ubuntu/index.adoc[Ubuntu 或 Debian 系统]下，选择相应的文件。


[cols="1a,1a"]
|===
| 路径和文件名 | Description 


| /debs/README  a| 
一个文本文件，用于描述 StorageGRID 下载文件中包含的所有文件。



| ./debs/NLF000000.txt  a| 
非生产 NetApp 许可证文件，可用于测试和概念验证部署。



| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
用于在 Ubuntu 或 Debian 主机上安装 StorageGRID 节点映像的 Deb 软件包。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
文件 ` /debs/storagegrid-webscale-images-version-SHA.deb` 的 MD5 校验和。



| ./debs/storagegrid-webscale-service-version-SHA.deb  a| 
用于在 Ubuntu 或 Debian 主机上安装 StorageGRID 主机服务的 Deb 软件包。



| 部署脚本工具 | Description 


| ./debs/configure-storagegrid.py  a| 
一种用于自动配置 StorageGRID 系统的 Python 脚本。



| ./debs/configure-sga.py  a| 
一种用于自动配置 StorageGRID 设备的 Python 脚本。



| ./debs/storagegrid-ssoauth.py  a| 
一个示例 Python 脚本，启用单点登录后，您可以使用该脚本登录到网格管理 API 。



| ./debs/configure-storaggrid.sample.json  a| 
与 `configure-storaggrid.py` 脚本结合使用的示例配置文件。



| ./debs/configure-storaggrid.blank.json  a| 
用于 `configure-storaggrid.py` 脚本的空配置文件。



| ./debs/Extras / Ansible  a| 
用于为 StorageGRID 容器部署配置 Ubuntu 或 Debian 主机的 Ansible 角色示例和攻略手册。您可以根据需要自定义角色或攻略手册。



| ./debs/ExtrS/API 架构  a| 
StorageGRID 的 API 架构。

* 注意 * ：在执行升级之前，如果您没有用于升级兼容性测试的非生产 StorageGRID 环境，则可以使用这些架构确认为使用 StorageGRID 管理 API 编写的任何代码都与新的 StorageGRID 版本兼容。

|===
. 如果要恢复 xref:../vmware/index.adoc[VMware 系统]下，选择相应的文件。


[cols="1a,1a"]
|===
| 路径和文件名 | Description 


| ./vSphere/README  a| 
一个文本文件，用于描述 StorageGRID 下载文件中包含的所有文件。



| ./vSphere/NLF000000.txt  a| 
一种免费许可证，不提供产品的任何支持授权。



| ./vsphere/netapp-sg-version-sha.vmdk  a| 
用作创建网格节点虚拟机的模板的虚拟机磁盘文件。



| ./vSphere/vsphere-primary-admin.OVF ./vsphere/vsphere-primary-admin.mf  a| 
用于部署主管理节点的开放式虚拟化格式模板文件（` .OVF` ）和清单文件（` .MF` ）。



| ./vSphere/vsphere-non-primary-admin.OVF ./vsphere/vsphere-non-primary-admin.mf  a| 
用于部署非主管理节点的模板文件（` .OVF` ）和清单文件（` .MF` ）。



| ./vSphere/vsphere-archive.OVF ./vsphere/vsphere-archive.mf  a| 
用于部署归档节点的模板文件（` .OVF` ）和清单文件（` .MF` ）。



| ./vSphere/vsphere-gateway.OVF ./vsphere/vsphere-gateway.mf  a| 
用于部署网关节点的模板文件（` .OVF` ）和清单文件（` .MF` ）。



| ./vSphere/vsphere-storage.OVF ./vsphere/vsphere-storage.mf  a| 
用于部署基于虚拟机的存储节点的模板文件（` .OVF` ）和清单文件（` .MF` ）。



| 部署脚本工具 | Description 


| ./vSphere/deploy-vsphere-ovftool.sh  a| 
Bash shell 脚本，用于自动部署虚拟网格节点。



| ./vSphere/deploy-vsphere-ovftool-sample.ini  a| 
与 `deept-vsphere-ovftool.sh` 脚本结合使用的示例配置文件。



| ./vSphere/configure-storagegrid.py  a| 
一种用于自动配置 StorageGRID 系统的 Python 脚本。



| ./vSphere/configure-sga.py  a| 
一种用于自动配置 StorageGRID 设备的 Python 脚本。



| ./vSphere/storagegrid-ssoauth.py  a| 
一个示例 Python 脚本，启用单点登录后，您可以使用该脚本登录到网格管理 API 。



| ./vsphere/configure-storaggrid.sample.json  a| 
与 `configure-storaggrid.py` 脚本结合使用的示例配置文件。



| ./vsphere/configure-storaggrid.blank.json  a| 
用于 `configure-storaggrid.py` 脚本的空配置文件。



| ./vsphere/ExtrS/API 架构  a| 
StorageGRID 的 API 架构。

* 注意 * ：在执行升级之前，如果您没有用于升级兼容性测试的非生产 StorageGRID 环境，则可以使用这些架构确认为使用 StorageGRID 管理 API 编写的任何代码都与新的 StorageGRID 版本兼容。

|===
. 如果要恢复基于 StorageGRID 设备的系统，请选择相应的文件。


[cols="1a,1a"]
|===
| 路径和文件名 | Description 


| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
用于在设备上安装 StorageGRID 节点映像的 Deb 软件包。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
StorageGRID 设备安装程序使用的 Deb 安装包的校验和，用于验证该软件包在上传后是否完好无损。

|===

NOTE: 对于设备安装，只有在需要避免网络流量时，才需要这些文件。设备可以从主管理节点下载所需文件。
