---
permalink: maintain/shutting-down-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, node shutdown, shut down node, node shut down 
summary: 您可以使用节点的命令 Shell 关闭网格节点。 
---
= 关闭网格节点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用节点的命令 Shell 关闭网格节点。

.您需要什么？ #8217 ；将需要什么
* 您必须具有 `passwords.txt` 文件。


在执行此操作步骤 之前，请查看以下注意事项：

* 通常，一次关闭的节点不应超过一个，以避免中断。
* 除非文档或技术支持明确指示，否则请勿在维护操作步骤 期间关闭节点。
* 关闭过程取决于节点的安装位置，如下所示：
+
** 关闭 VMware 节点将关闭虚拟机。
** 关闭 Linux 节点将关闭容器。
** 关闭 StorageGRID 设备节点将关闭计算控制器。


* 如果您计划关闭一个站点上的多个存储节点、请在关闭这些节点之前停止在该站点上载入对象大约一小时。
+
如果任何ILM规则使用*双提交*载入选项(或者某个规则使用*平衡*选项、并且无法立即创建所有必需的副本)、则StorageGRID 会立即将任何新载入的对象提交到同一站点上的两个存储节点、并在稍后对ILM进行评估。如果某个站点上的多个存储节点关闭、则在关闭期间、您可能无法访问新载入的对象。如果站点上的可用存储节点太少、写入操作也可能失败。



.步骤
. 登录到网格节点：
+
.. 输入以下命令： `ssh admin@ grid_node_ip_`
.. 输入 `passwords.txt` 文件中列出的密码。
.. 输入以下命令切换到 root ： `su -`
.. 输入 `passwords.txt` 文件中列出的密码。


+
以 root 用户身份登录时，提示符将从 ` $` 更改为 ` #` 。

. 停止所有服务： `service servermanager stop`
+
服务可能需要长达 15 分钟才能关闭，您可能需要远程登录到系统以监控关闭过程。

. 如果此节点正在 VMware 虚拟机上运行或它是设备节点，请使用问题描述 关闭命令： `shutdown -h now`
+
执行此步骤，无论 `sservice servermanager stop` 命令的结果如何。

+

NOTE: 在设备节点上执行问题描述 `shutdown -h now` 命令后，必须重新启动设备以重新启动节点。

+
对于设备，此命令将关闭控制器，但设备仍处于打开状态。您必须完成下一步。

. 如果要关闭设备节点：
+
** 对于 SG100 或 SG1000 服务设备
+
... 关闭设备电源。
... 等待蓝色电源 LED 熄灭。


** 对于 SG6000 设备
+
... 等待存储控制器背面的绿色缓存活动 LED 熄灭。
+
当需要将缓存的数据写入驱动器时，此 LED 亮起。您必须等待此 LED 关闭，然后再关闭电源。

... 关闭设备电源，然后等待蓝色电源 LED 熄灭。


** 对于 SG5700 设备
+
... 等待存储控制器背面的绿色缓存活动 LED 熄灭。
+
当需要将缓存的数据写入驱动器时，此 LED 亮起。您必须等待此 LED 关闭，然后再关闭电源。

... 关闭设备电源，等待所有 LED 和七段显示活动停止。






xref:../admin/index.adoc[管理 StorageGRID]
