---
permalink: primer/configuring-network-settings.html 
sidebar: sidebar 
keywords: network settings, configure, configuring, configuration, domain name, virtual hosted-style requests 
summary: 您可以从网格管理器配置各种网络设置，以微调 StorageGRID 系统的运行。 
---
= 配置网络设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以从网格管理器配置各种网络设置，以微调 StorageGRID 系统的运行。



== 域名

如果您计划支持 S3 虚拟托管模式请求，则必须配置 S3 客户端连接到的端点域名列表。例如， `s3.example.com` ， `s3.example.co.uk` 和 `s3-east.example.com` 。

配置的服务器证书必须与端点域名匹配。



== 高可用性组

您可以使用高可用性（ High Availability ， HA ）组为 S3 和 Swift 客户端提供高可用性数据连接，或者为 Grid Manager 和租户管理器提供高可用性连接。

创建 HA 组时，您可以为一个或多个节点选择网络接口。每个 HA 组均可访问选定节点上的共享服务。

* 包括网关节点，管理节点或两者上的接口的 HA 组可为 S3 和 Swift 客户端提供高可用性数据连接。
* 管理节点上包含接口的 HA 组仅提供与网格管理器和租户管理器的高可用性连接。


这些接口可以属于网格网络（ eth0 ），客户端网络（ eth2 ）或 VLAN 网络。

您最多可以为每个 HA 组分配 10 个虚拟 IP （ VIP ）地址。您可以将一个接口指定为主接口，并按优先级顺序对任何其他接口进行排名。主接口是活动接口，除非发生故障。如果活动接口发生故障， VIP 地址将按优先级顺序移至第一个备份接口。如果该接口发生故障， VIP 地址将移至下一个备份接口，依此类推。



== 链路成本

您可以调整链路成本以反映站点之间的延迟。如果存在两个或更多数据中心站点，则链路成本会优先考虑应由哪个数据中心站点提供请求的服务。



== 负载平衡器端点

您可以使用负载平衡器处理从 S3 和 Swift 客户端载入和检索工作负载。负载平衡通过在多个存储节点之间分布工作负载和连接来最大限度地提高速度和连接容量。

如果要使用管理节点和网关节点上包含的 StorageGRID 负载平衡器服务，则必须配置一个或多个负载平衡器端点。每个端点都为 S3 和 Swift 向存储节点发出的请求定义了一个网关节点或管理节点端口。



== 流量分类

您可以创建流量分类策略来识别和处理不同类型的网络流量，包括与特定分段，租户，客户端子网或负载平衡器端点相关的流量。这些策略有助于限制和监控流量。



== VLAN 接口

您可以创建虚拟 LAN （ VLAN ）接口来隔离流量并对流量进行分区，以提高安全性，灵活性和性能。每个 VLAN 接口都与管理节点和网关节点上的一个或多个父接口相关联。您可以在 HA 组和负载平衡器端点中使用 VLAN 接口，按应用程序或租户隔离客户端或管理流量。

例如，您的网络可能使用 VLAN 100 传输 FabricPool 流量，而使用 VLAN 200 传输归档应用程序。

.相关信息
* xref:../admin/index.adoc[管理 StorageGRID]
* xref:managing-tenants-and-client-connections.adoc[管理租户和客户端连接]

