---
permalink: primer/managing-tenants-and-client-connections.html 
sidebar: sidebar 
keywords: tenant, client, connect, connection 
summary: 作为网格管理员，您可以创建和管理 S3 和 Swift 客户端用于存储和检索对象的租户帐户，并管理控制客户端连接到 StorageGRID 系统的方式的配置选项。 
---
= 管理租户和客户端连接
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
作为网格管理员，您可以创建和管理 S3 和 Swift 客户端用于存储和检索对象的租户帐户，并管理控制客户端连接到 StorageGRID 系统的方式的配置选项。



== 租户帐户

租户帐户允许您指定谁可以使用 StorageGRID 系统存储和检索对象，以及他们可以使用哪些功能。租户帐户允许支持 S3 REST API 或 Swift REST API 的客户端应用程序在 StorageGRID 上存储和检索对象。每个租户帐户都使用 S3 客户端协议或 Swift 客户端协议。

您必须为要用于在 StorageGRID 系统上存储对象的每个客户端协议至少创建一个租户帐户。或者，如果要将系统上存储的对象隔离为不同的实体，则可以创建其他租户帐户。每个租户帐户都有自己的联合或本地组和用户，以及自己的分段（用于 Swift 的容器）和对象。

您可以使用网格管理器或网格管理 API 创建租户帐户。创建租户帐户时，您可以指定以下信息：

* 租户的显示名称（租户的帐户 ID 会自动分配，不能更改）。
* 租户帐户是使用 S3 还是 Swift 。
* 对于 S3 租户帐户：是否允许租户帐户使用平台服务。如果允许使用平台服务，则必须对网格进行配置，以支持使用这些服务。
* （可选）租户帐户的存储配额—租户对象可用的最大 GB ， TB 或 PB 数。租户的存储配额表示逻辑容量（对象大小），而不是物理容量（磁盘大小）。
* 如果为 StorageGRID 系统启用了身份联合，则哪个联合组具有 " 根访问 " 权限来配置租户帐户。
* 如果 StorageGRID 系统未使用单点登录（ SSO ），则表示租户帐户是使用自己的身份源还是共享网格的身份源，以及租户的本地 root 用户的初始密码。


如果 S3 租户帐户需要符合法规要求，网格管理员可以为 StorageGRID 系统启用全局 S3 对象锁定设置。如果为系统启用了 S3 对象锁定，则所有 S3 租户帐户都可以在启用了 S3 对象锁定的情况下创建存储分段，然后为该存储分段中的对象版本指定保留和合法保留设置。

创建租户帐户后，租户用户可以登录到租户管理器。



== 客户端与 StorageGRID 节点的连接

租户用户必须先确定这些客户端如何连接到 StorageGRID 节点，然后才能使用 S3 或 Swift 客户端在 StorageGRID 中存储和检索数据。

客户端应用程序可以通过连接到以下任一项来存储或检索对象：

* 管理节点或网关节点上的负载平衡器服务。建议使用此连接。
* 网关节点上的 CLB 服务。
+

NOTE: CLB 服务已弃用。

* 存储节点，具有或不具有外部负载平衡器。


在配置 StorageGRID 以使客户端能够使用负载平衡器服务时，您需要执行以下步骤：

. 也可以配置高可用性（ HA ）组。如果创建 HA 组，则多个管理节点和网关节点的接口将置于主动备份配置中。客户端连接使用 HA 组的虚拟 IP 地址进行。
. 为负载平衡器服务配置端点。管理节点或网关节点上的负载平衡器服务会将传入的网络连接从客户端应用程序分发到存储节点。创建负载平衡器端点时，您可以指定端口号，端点是否接受 HTTP 或 HTTPS 连接，将使用此端点的客户端类型（ S3 或 Swift ）以及用于 HTTPS 连接的证书（如果适用）。
. （可选）指定节点的客户端网络不可信，以确保与节点的客户端网络的所有连接都发生在负载平衡器端点上。


.相关信息
* xref:../admin/index.adoc[管理 StorageGRID]
* xref:../tenant/index.adoc[使用租户帐户]
* xref:../s3/index.adoc[使用 S3]
* xref:../swift/index.adoc[使用 Swift]
* xref:exploring-tenant-manager.adoc[浏览租户管理器]
* xref:configuring-network-settings.adoc[配置网络设置]

