---
permalink: primer/using-snmp-monitoring.html 
sidebar: sidebar 
keywords: snmp, simple network management protocol, agent, trap, inform, mib 
summary: 如果要使用简单网络管理协议（ SNMP\ ）监控 StorageGRID ，可以使用网格管理器配置 SNMP 代理。 
---
= 使用 SNMP 监控
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要使用简单网络管理协议（ Simple Network Management Protocol ， SNMP ）监控 StorageGRID ，可以使用网格管理器配置 SNMP 代理。

每个 StorageGRID 节点都运行一个 SNMP 代理或守护进程，该代理或守护进程可提供一个管理信息库（ Management Information Base ， MIB ）。StorageGRID MIB 包含警报和警报的表和通知定义。每个 StorageGRID 节点还支持一组 MIB-II 对象。

最初，所有节点上都会禁用 SNMP 。配置 SNMP 代理时，所有 StorageGRID 节点都会收到相同的配置。

StorageGRID SNMP 代理支持所有三个版本的 SNMP 协议。该代理可为查询提供只读 MIB 访问权限，并可向管理系统发送两种类型的事件驱动型通知：

* * 陷阱 * 是 SNMP 代理发送的通知，不需要管理系统确认。陷阱用于通知管理系统 StorageGRID 中发生了某种情况，例如触发警报。所有三个版本的 SNMP 均支持陷阱。
* * 通知 * 与陷阱类似，但它们需要管理系统确认。如果 SNMP 代理未在特定时间内收到确认，则会重新发送通知，直到收到确认或达到最大重试值为止。SNMPv2c 和 SNMPv3 支持 INFORM 。


在以下情况下会发送陷阱和通知通知通知：

* 默认或自定义警报将在任何严重性级别触发。要禁止警报的 SNMP 通知，您必须为此警报配置静默。警报通知由配置为首选发送方的任何管理节点发送。
* 某些警报（旧系统）会在指定的严重性级别或更高级别触发。
+

NOTE: 不会针对每个警报或每个警报严重性发送 SNMP 通知。



* 相关信息 *

* xref:../monitor/index.adoc[监控和故障排除]

