---
permalink: sg5700/optional-changing-raid-mode-sg5760-only.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, raid, raid mode, change, changing, modify, DDP, ddp16, raid6 
summary: 如果您的 SG5760 包含 60 个驱动器，则可以更改为其他 RAID 模式以满足存储和恢复要求。您只能在部署 StorageGRID 设备存储节点之前更改此模式。 
---
= 可选：更改 RAID 模式（仅限 SG5760 ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您的 SG5760 包含 60 个驱动器，则可以更改为其他 RAID 模式以满足存储和恢复要求。您只能在部署 StorageGRID 设备存储节点之前更改此模式。

.您需要的内容
* 您已安装 SG5760 。如果您使用的是 SG5712 ，则必须使用 DDP 模式。
* 您正在使用可以连接到 StorageGRID 的任何客户端。
* 客户端具有 xref:../admin/web-browser-requirements.adoc[支持的 Web 浏览器]。


.关于此任务
在将 SG5760 设备部署为存储节点之前，您可以选择以下卷配置选项之一：

* * DDP * ：此模式每八个数据驱动器使用两个奇偶校验驱动器。这是所有设备的默认和建议模式。与 RAID6 相比， DDP 可提高系统性能，缩短驱动器发生故障后的重建时间，并简化管理。DDP 还可在 60 驱动器设备中提供抽盒丢失保护。
* * DDP16* ：此模式每 16 个数据驱动器使用两个奇偶校验驱动器，因此与 DDP 相比，存储效率更高。与 RAID6 相比， DDP16 可提高系统性能，缩短驱动器故障后的重建时间，简化管理并提供同等的存储效率。要使用 DDP16 模式，您的配置必须至少包含 20 个驱动器。DDP16 不提供抽盒丢失保护。
* * RAID6* ：此模式每 16 个或更多数据驱动器使用两个奇偶校验驱动器。要使用 RAID 6 模式，您的配置必须至少包含 20 个驱动器。虽然与 DDP 相比， RAID6 可以提高设备的存储效率，但不建议在大多数 StorageGRID 环境中使用。



IMPORTANT: 如果已配置任何卷或先前已安装 StorageGRID ，则更改 RAID 模式会删除和更换这些卷。这些卷上的所有数据都将丢失。

.步骤
. 使用服务笔记本电脑打开 Web 浏览器并访问 StorageGRID 设备安装程序： + ` * https://_E5700SG_Controller_IP_:8443*`
+
其中， ` _E5700SG_Controller_IP_` 是 E5700SG 控制器的任何 IP 地址。

. 选择 * 高级 * > * RAID 模式 * 。
. 在 * 配置 RAID 模式 * 页面上，从模式下拉列表中选择所需的 RAID 模式。
. 单击 * 保存 * 。


.相关信息
http://mysupport.netapp.com/info/web/ECMP1658252.html["NetApp E 系列系统文档站点"^]
