---
permalink: expand/gather-required-materials.html 
sidebar: sidebar 
keywords: expand, expansion, planning, storagrid files 
summary: 在执行扩展操作之前，请收集相关材料并安装和配置任何新的硬件和网络。 
---
= 收集所需材料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在执行扩展操作之前，请收集相关材料并安装和配置任何新的硬件和网络。

[cols="1a,2a"]
|===
| 项目 | 注释： 


 a| 
StorageGRID 安装归档
 a| 
如果要添加新的网格节点或新站点，则必须下载并提取 StorageGRID 安装归档。您必须使用网格上当前运行的相同版本。

有关详细信息，请参见的说明 <<download-and-extract-install-files,下载并提取 StorageGRID 安装文件>>。

* 注意： * 如果要向现有存储节点添加新存储卷或安装新的 StorageGRID 设备，则不需要下载文件。



 a| 
服务笔记本电脑
 a| 
服务笔记本电脑具有以下功能：

* 网络端口
* SSH 客户端（例如 PuTTY ）
* xref:../admin/web-browser-requirements.adoc[支持的 Web 浏览器]




 a| 
`passwords.txt` file
 a| 
包含访问命令行上的网格节点所需的密码。包含在恢复包中。



 a| 
配置密码短语
 a| 
首次安装 StorageGRID 系统时，系统会创建并记录密码短语。配置密码短语不在 `passwords.txt` 文件中。



 a| 
StorageGRID 文档
 a| 
* xref:../admin/index.adoc[管理 StorageGRID]
* xref:../release-notes/index.adoc[发行说明]
* 适用于您的平台的安装说明
+
** xref:../rhel/index.adoc[安装 Red Hat Enterprise Linux 或 CentOS]
** xref:../ubuntu/index.adoc[安装 Ubuntu 或 Debian]
** xref:../vmware/index.adoc[安装 VMware]






 a| 
适用于您的平台的最新文档
 a| 
有关支持的版本，请参见 https://mysupport.netapp.com/matrix["互操作性表"^]。

|===


== 下载并提取 StorageGRID 安装文件

.【下载并提取安装文件】
在添加新网格节点或新站点之前，必须下载相应的 StorageGRID 安装归档并提取文件。

.关于此任务
您必须使用网格上当前运行的 StorageGRID 版本执行扩展操作。

.步骤
. 转到 StorageGRID 的 "NetApp 下载 " 页面。
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 下载： StorageGRID"^]

. 选择网格上当前运行的 StorageGRID 版本。
. 使用您的 NetApp 帐户的用户名和密码登录。
. 阅读最终用户许可协议，选中复选框，然后选择 * 接受并继续 * 。
. 在下载页面的 * 安装 StorageGRID * 列中，为您的平台选择 ` .tgz` 或 ` .zip` 文件。
+
安装归档文件中显示的版本必须与当前安装的软件版本匹配。

+
如果您在服务笔记本电脑上运行 Windows ，请使用 ` .zip` 文件。

+
[cols="1a,2a"]
|===
| 平台 | 安装归档 


 a| 
Red Hat Enterprise Linux 或 CentOS
| `storageGRID-Webscale -_version_-RPM-_uniqueID_.zip` `StorageGRID-Webscale -_version_-RPM-_uniqueID_.tgz` 


 a| 
Ubuntu ， Debian 或设备
| `storageGRID-Webscale -_version_-Deb-uniqueID_.zip` `StorageGRID-Webscale -_version_-Deb-uniqueID_.tgz` 


 a| 
VMware
| `storageGRID-Webscale -_version_-vmware-_uniqueID_.zip` `StorageGRID-Webscale -_version_-vmware-_uniqueID_.tgz` 


 a| 
OpenStack/ 其他虚拟机管理程序
 a| 
要在 OpenStack 上扩展现有部署，您必须部署一个运行上述受支持 Linux 分发版本之一的虚拟机，并按照适用于 Linux 的相应说明进行操作。

|===
. 下载并提取归档文件。
. 按照适用于您的平台的步骤，根据您的平台，计划的网格拓扑以及您将如何扩展 StorageGRID 系统来选择所需的文件。
+
步骤中为每个平台列出的路径与归档文件安装的顶级目录相对。

. 如果要扩展 Red Hat Enterprise Linux 或 CentOS 系统，请选择相应的文件。


[cols="1a,1a"]
|===
| 路径和文件名 | Description 


| ./rpms/README  a| 
一个文本文件，用于描述 StorageGRID 下载文件中包含的所有文件。



| ./rpms/NLF000000.txt  a| 
一种免费许可证，不提供产品的任何支持授权。



| ./rpms/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
RPM 软件包，用于在 RHEL 或 CentOS 主机上安装 StorageGRID 节点映像。



| ./rpms/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
RPM 软件包，用于在 RHEL 或 CentOS 主机上安装 StorageGRID 主机服务。



| 部署脚本工具 | Description 


| ./rpms/configure-storagegrid.py  a| 
一种用于自动配置 StorageGRID 系统的 Python 脚本。



| ./rpms/configure-sga.py  a| 
一种用于自动配置 StorageGRID 设备的 Python 脚本。



| ./rpms/configure-storagegrid.sample.json  a| 
与 `configure-storaggrid.py` 脚本结合使用的示例配置文件。



| ./rpms/storagegrid-ssoauth.py  a| 
一个示例 Python 脚本，启用单点登录后，您可以使用该脚本登录到网格管理 API 。



| ./rpms/configure-storagegrid.blank.json  a| 
用于 `configure-storaggrid.py` 脚本的空配置文件。



| ./rpms/Extras 或 Ansible  a| 
用于为 StorageGRID 容器部署配置 RHEL 或 CentOS 主机的 Ansible 角色示例和攻略手册。您可以根据需要自定义角色或攻略手册。



| ./rpms/Extras 或 API 架构  a| 
StorageGRID 的 API 架构。

* 注意 * ：在执行升级之前，如果您没有用于升级兼容性测试的非生产 StorageGRID 环境，则可以使用这些架构确认为使用 StorageGRID 管理 API 编写的任何代码都与新的 StorageGRID 版本兼容。

|===
. 如果要扩展 Ubuntu 或 Debian 系统，请选择相应的文件。


[cols="1a,1a"]
|===
| 路径和文件名 | Description 


| /debs/README  a| 
一个文本文件，用于描述 StorageGRID 下载文件中包含的所有文件。



| ./debs/NLF000000.txt  a| 
非生产 NetApp 许可证文件，可用于测试和概念验证部署。



| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
用于在 Ubuntu 或 Debian 主机上安装 StorageGRID 节点映像的 Deb 软件包。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
文件 ` /debs/storagegrid-webscale-images-version-SHA.deb` 的 MD5 校验和。



| ./debs/storagegrid-webscale-service-version-SHA.deb  a| 
用于在 Ubuntu 或 Debian 主机上安装 StorageGRID 主机服务的 Deb 软件包。



| 部署脚本工具 | Description 


| ./debs/configure-storagegrid.py  a| 
一种用于自动配置 StorageGRID 系统的 Python 脚本。



| ./debs/configure-sga.py  a| 
一种用于自动配置 StorageGRID 设备的 Python 脚本。



| ./debs/storagegrid-ssoauth.py  a| 
一个示例 Python 脚本，启用单点登录后，您可以使用该脚本登录到网格管理 API 。



| ./debs/configure-storaggrid.sample.json  a| 
与 `configure-storaggrid.py` 脚本结合使用的示例配置文件。



| ./debs/configure-storaggrid.blank.json  a| 
用于 `configure-storaggrid.py` 脚本的空配置文件。



| ./debs/Extras / Ansible  a| 
用于为 StorageGRID 容器部署配置 Ubuntu 或 Debian 主机的 Ansible 角色示例和攻略手册。您可以根据需要自定义角色或攻略手册。



| ./debs/ExtrS/API 架构  a| 
StorageGRID 的 API 架构。

* 注意 * ：在执行升级之前，如果您没有用于升级兼容性测试的非生产 StorageGRID 环境，则可以使用这些架构确认为使用 StorageGRID 管理 API 编写的任何代码都与新的 StorageGRID 版本兼容。

|===
. 如果要扩展 VMware 系统，请选择相应的文件。


[cols="1a,1a"]
|===
| 路径和文件名 | Description 


| ./vSphere/README  a| 
一个文本文件，用于描述 StorageGRID 下载文件中包含的所有文件。



| ./vSphere/NLF000000.txt  a| 
一种免费许可证，不提供产品的任何支持授权。



| ./vsphere/netapp-sg-version-sha.vmdk  a| 
用作创建网格节点虚拟机的模板的虚拟机磁盘文件。



| ./vSphere/vsphere-primary-admin.OVF ./vsphere/vsphere-primary-admin.mf  a| 
用于部署主管理节点的开放式虚拟化格式模板文件（` .OVF` ）和清单文件（` .MF` ）。



| ./vSphere/vsphere-non-primary-admin.OVF ./vsphere/vsphere-non-primary-admin.mf  a| 
用于部署非主管理节点的模板文件（` .OVF` ）和清单文件（` .MF` ）。



| ./vSphere/vsphere-archive.OVF ./vsphere/vsphere-archive.mf  a| 
用于部署归档节点的模板文件（` .OVF` ）和清单文件（` .MF` ）。



| ./vSphere/vsphere-gateway.OVF ./vsphere/vsphere-gateway.mf  a| 
用于部署网关节点的模板文件（` .OVF` ）和清单文件（` .MF` ）。



| ./vSphere/vsphere-storage.OVF ./vsphere/vsphere-storage.mf  a| 
用于部署基于虚拟机的存储节点的模板文件（` .OVF` ）和清单文件（` .MF` ）。



| 部署脚本工具 | Description 


| ./vSphere/deploy-vsphere-ovftool.sh  a| 
Bash shell 脚本，用于自动部署虚拟网格节点。



| ./vSphere/deploy-vsphere-ovftool-sample.ini  a| 
与 `deept-vsphere-ovftool.sh` 脚本结合使用的示例配置文件。



| ./vSphere/configure-storagegrid.py  a| 
一种用于自动配置 StorageGRID 系统的 Python 脚本。



| ./vSphere/configure-sga.py  a| 
一种用于自动配置 StorageGRID 设备的 Python 脚本。



| ./vSphere/storagegrid-ssoauth.py  a| 
一个示例 Python 脚本，启用单点登录后，您可以使用该脚本登录到网格管理 API 。



| ./vsphere/configure-storaggrid.sample.json  a| 
与 `configure-storaggrid.py` 脚本结合使用的示例配置文件。



| ./vsphere/configure-storaggrid.blank.json  a| 
用于 `configure-storaggrid.py` 脚本的空配置文件。



| ./vsphere/ExtrS/API 架构  a| 
StorageGRID 的 API 架构。

* 注意 * ：在执行升级之前，如果您没有用于升级兼容性测试的非生产 StorageGRID 环境，则可以使用这些架构确认为使用 StorageGRID 管理 API 编写的任何代码都与新的 StorageGRID 版本兼容。

|===
. 如果要扩展基于 StorageGRID 设备的系统，请选择相应的文件。


[cols="1a,1a"]
|===
| 路径和文件名 | Description 


| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
用于在设备上安装 StorageGRID 节点映像的 Deb 软件包。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
StorageGRID 设备安装程序使用的 Deb 安装包的校验和，用于验证该软件包在上传后是否完好无损。

|===

NOTE: 对于设备安装，只有在需要避免网络流量时，才需要这些文件。设备可以从主管理节点下载所需文件。



== 验证硬件和网络连接

开始扩展 StorageGRID 系统之前，请确保满足以下要求：

* 已安装并配置支持新网格节点或新站点所需的硬件。
* 所有新节点都具有指向所有现有节点和新节点的双向通信路径（网格网络的一项要求）。
* 主管理节点可以与用于托管 StorageGRID 系统的所有扩展服务器进行通信。
* 如果任何新节点的子网上有一个网格网络 IP 地址，而此地址以前未使用过，则表示您已使用 xref:updating-subnets-for-grid-network.adoc[已添加新子网] 到网格网络子网列表。否则，您必须取消扩展，添加新子网并重新启动操作步骤 。
* 您未在网格节点之间或 StorageGRID 站点之间的网格网络上使用网络地址转换（ Network Address Translation ， NAT ）。如果您对网格网络使用专用 IPv4 地址，则这些地址必须可从每个站点的每个网格节点直接路由。只有在使用对网格中的所有节点都透明的通道应用程序时，才支持使用 NAT 在公有 网段中桥接网格网络，这意味着网格节点不需要了解公有 IP 地址。
+
此 NAT 限制特定于网格节点和网格网络。您可以根据需要在外部客户端和网格节点之间使用 NAT ，例如为网关节点提供公有 IP 地址。


