---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure 
summary: 在某些情况下，您可能需要在添加新存储节点后重新平衡经过纠删编码的数据。 
---
= 添加存储节点后重新平衡经过纠删编码的数据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在某些情况下，您可能需要在添加新存储节点后重新平衡经过纠删编码的数据。

.您需要什么？ #8217 ；将需要什么
* 您已完成添加新存储节点的扩展步骤。
* 您已查看 xref:considerations-for-rebalancing-erasure-coded-data.adoc[重新平衡经过纠删编码的数据的注意事项]。
+

IMPORTANT: 只有在为站点上的一个或多个存储节点触发了 * 对象存储空间不足 * 警报且您无法添加建议数量的新存储节点时，才能执行此操作步骤 。

* 您了解此操作步骤 不会移动复制的对象数据，并且在确定将纠删编码的数据移动到何处时， EC 重新平衡操作步骤 不会考虑每个存储节点上的复制数据使用情况。
* 您已有 `passwords.txt` 文件。


当 EC 重新平衡操作步骤 运行时， ILM 操作以及 S3 和 Swift 客户端操作的性能可能会受到影响。因此，您只能在有限情况下执行此操作步骤 。


NOTE: EC 重新平衡操作步骤 会临时预留大量存储。可能会触发存储警报，但会在重新平衡完成后解决。如果没有足够的存储空间用于预留， EC 重新平衡操作步骤 将失败。无论操作步骤 出现故障还是成功， EC 重新平衡操作步骤 完成后都会释放存储预留。

[NOTE]
====
如果需要超过 24 小时才能完成 EC 重新平衡操作步骤 期间用于上传对象（或对象部件）的 S3 和 Swift API 操作可能会失败。如果适用的 ILM 规则在载入时使用严格或平衡的放置方式，则长时间的 PUT 操作将失败。此时将报告以下错误：

`500 内部服务器错误`

====
.步骤
. 【 Review object_storage]] 查看计划重新平衡的站点的当前对象存储详细信息。
+
.. 选择 * 节点 * 。
.. 选择站点上的第一个存储节点。
.. 选择 * 存储 * 选项卡。
.. 将光标悬停在 " 已用存储 - 对象数据 " 图表上，可查看存储节点上当前复制的数据量以及经过纠删编码的数据。
.. 重复上述步骤以查看站点上的其他存储节点。


. 登录到主管理节点：
+
.. 输入以下命令： `ssh admin@ primary_Admin_Node_IP_`
.. 输入 `passwords.txt` 文件中列出的密码。
.. 输入以下命令切换到 root ： `su -`
.. 输入 `passwords.txt` 文件中列出的密码。
+
以 root 用户身份登录时，提示符将从 ` $` 更改为 ` #` 。



. 输入以下命令：
+
`rebalance-data start -site "_site-name_"`

+
对于 ` "_site-name_"` ，请指定添加新存储节点的第一个站点。请用引号将 `site-name` 括起来。

+
此时将启动 EC 重新平衡操作步骤 ，并返回作业 ID 。

. 复制作业 ID 。
. 监控 EC 重新平衡操作步骤 的状态。
+
** 要查看单个 EC 重新平衡操作步骤 的状态，请执行以下操作：
+
`rebalance-data status -job-id _job-id_`

+
对于 ` 作业 ID` ，指定启动操作步骤 时返回的 ID 。

** 要查看当前 EC 重新平衡操作步骤 的状态以及先前完成的任何过程：
+
`rebalance-data status`

+
[NOTE]
====
要获取有关 rebalance-data 命令的帮助，请执行以下操作：

`rebalance-data — help`

====
** 要查看当前作业的估计完成时间和完成百分比，请选择 * 支持 * > * 工具 * > * 指标 * 。然后，在 Grafana 部分中选择 * EC Overview* 。查看 * 网格 EC 作业预计完成时间 * 和 * 网格 EC 作业已完成百分比 * 信息板。


. 根据返回的状态执行其他步骤：
+
** 如果状态为 `In progress` ，则 EC 重新平衡操作仍在运行。您应定期监控操作步骤 ，直到其完成。
** 如果状态为 `failure` ，请执行 ,失败步骤。
** 如果状态为 `Success` ，请执行 ,成功步骤。


. 如果 EC 重新平衡操作步骤 生成的负载过多（例如，载入操作受到影响），请暂停操作步骤 。
+
`rebalance-data pause -job-id _job-id_`

. 如果您需要终止 EC 重新平衡操作步骤 （例如，以便执行 StorageGRID 软件升级），请输入以下内容：
+
`rebalance-data terminate -job-id _job-id_`

+

NOTE: 终止 EC 重新平衡操作步骤 后，已移动的所有数据片段都将保留在新位置。数据不会移回原始位置。

. 【 rebalance_fail 】如果 EC 重新平衡操作步骤 的状态为 `failure` ，请执行以下步骤：
+
.. 确认站点上的所有存储节点均已连接到网格。
.. 检查并解决可能影响这些存储节点的任何警报。
+
有关特定警报的信息，请参见监控和故障排除说明。

.. 重新启动 EC 重新平衡操作步骤 ： + `rebalance-data start – -job-id _job-id_`
.. 如果 EC 重新平衡操作步骤 的状态仍为 `Failure` ，请联系技术支持。


. `SEC 重新平衡操作步骤 的状态为 " 无 ccess` " （可选） ,查看对象存储 以查看此站点的更新详细信息。
+
现在，经过纠删编码的数据应在站点的存储节点之间更加平衡。

. 如果要在多个站点上使用纠删编码，请对所有其他受影响站点运行此操作步骤 。

