---
permalink: ilm/creating-ilm-policy.html 
sidebar: sidebar 
keywords: create ILM policy, information lifecycle policy considerations 
summary: 创建 ILM 策略时，首先要选择并排列 ILM 规则。然后，您可以根据先前载入的对象模拟建议的策略，以验证其行为。如果您对建议的策略按预期运行感到满意，则可以激活此策略以创建活动策略。 
---
= 创建 ILM 策略：概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
创建 ILM 策略时，首先要选择并排列 ILM 规则。然后，您可以根据先前载入的对象模拟建议的策略，以验证其行为。如果您对建议的策略按预期运行感到满意，则可以激活此策略以创建活动策略。


CAUTION: 配置不正确的 ILM 策略可能导致无法恢复的数据丢失。激活 ILM 策略之前，请仔细查看 ILM 策略及其 ILM 规则，然后模拟 ILM 策略。请始终确认 ILM 策略将按预期运行。



== 创建 ILM 策略的注意事项

* 仅在测试系统中使用系统的内置策略基线 2 副本策略。此策略中的 Make 2 Copies 规则使用包含所有站点的所有存储节点存储池。如果 StorageGRID 系统具有多个站点，则一个对象的两个副本可能会放置在同一站点上。
* 在设计新策略时，请考虑可能会输入到网格中的所有不同类型的对象。确保此策略包含与这些对象匹配并根据需要放置这些对象的规则。
* 尽量使 ILM 策略简单。这样可以避免在随时间推移对 StorageGRID 系统进行更改时，对象数据无法按预期得到保护的潜在危险情况。
* 确保策略中的规则顺序正确。激活策略后，新对象和现有对象将按列出的顺序从顶部开始进行评估。例如，如果策略中的第一个规则与某个对象匹配，则任何其他规则都不会评估该规则。
* 每个 ILM 策略中的最后一个规则是默认 ILM 规则，它不能使用任何筛选器。如果某个对象未被其他规则匹配，则默认规则将控制该对象的放置位置以及保留时间。
* 在激活新策略之前，请查看此策略对现有对象的放置所做的任何更改。在评估和实施新放置时，更改现有对象的位置可能会导致临时资源问题。

