---
permalink: ilm/guidelines-for-creating-storage-pools.html 
sidebar: sidebar 
keywords: storage pool guidelines 
summary: 配置和使用存储池时，请遵循以下准则。 
---
= 创建存储池的准则
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配置和使用存储池时，请遵循以下准则。



== 所有存储池的准则

* StorageGRID 包括一个默认存储池 " 所有存储节点 " ，该存储池使用默认站点，所有站点以及默认存储级别 " 所有存储节点 " 。每当您添加新的数据中心站点时，系统都会自动更新所有存储节点存储池。
+

NOTE: 建议不要使用所有存储节点存储池或所有站点站点站点，因为这些项目会自动更新，以包括您在扩展中添加的任何新站点，而这可能不是您希望的行为。在使用所有存储节点存储池或默认站点之前，请仔细阅读有关复制的副本和经过纠删编码的副本的准则。

* 尽可能简化存储池配置。创建的存储池不要超过所需数量。
* 创建具有尽可能多节点的存储池。每个存储池应包含两个或更多节点。如果节点不可用，则节点不足的存储池可以对发生原因 ILM 进行回退。
* 避免创建或使用重叠的存储池（包含一个或多个相同节点）。如果存储池重叠，则可能会在同一节点上保存多个对象数据副本。




== 用于复制副本的存储池准则

* 为每个站点创建不同的存储池。然后，在每个规则的放置说明中指定一个或多个特定于站点的存储池。对每个站点使用存储池可确保复制的对象副本准确放置在所需位置（例如，每个站点上的每个对象一个副本，以实现站点丢失保护）。
* 如果在扩展中添加站点，请为新站点创建一个新存储池。然后，更新 ILM 规则以控制新站点上存储的对象。
* 通常，不要使用默认存储池，所有存储节点或包含默认站点的任何存储池，即所有站点。




== 用于擦除编码副本的存储池准则

* 您不能对纠删编码的数据使用归档节点。
* 存储池中包含的存储节点和站点数量决定了可用的纠删编码方案。
* 如果存储池仅包含两个站点，则不能使用该存储池进行纠删编码。对于具有两个站点的存储池，没有可用的纠删编码方案。
* 通常，不要使用默认存储池，所有存储节点或包含默认站点的任何存储池，也不要使用任何擦除编码配置文件中的所有站点。
+

NOTE: 如果您的网格仅包含一个站点，则系统将阻止您使用擦除编码配置文件中的所有存储节点存储池或所有站点默认站点。此行为可防止添加第二个站点时擦除编码配置文件变得无效。

* 如果您的吞吐量要求较高，则在站点之间的网络延迟超过 100 毫秒时，建议不要创建包含多个站点的存储池。随着延迟增加， StorageGRID 创建，放置和检索对象片段的速率会因 TCP 网络吞吐量降低而大幅下降。吞吐量的下降会影响对象载入和检索的最大可实现速率（如果选择 " 严格 " 或 " 平衡 " 作为 " 载入 " 行为），或者可能导致 ILM 队列回退（如果选择 " 双提交 " 作为 " 载入 " 行为）。
* 如果可能，存储池中的存储节点数应超过您选择的纠删编码方案所需的最小存储节点数。例如，如果您使用 6+3 纠删编码方案，则必须至少有九个存储节点。但是，建议每个站点至少另外配置一个存储节点。
* 尽可能均匀地在各个站点之间分布存储节点。例如，要支持 6+3 纠删编码方案，请配置一个存储池，使其在三个站点中至少包含三个存储节点。




== 用于归档副本的存储池准则

* 您不能创建同时包含存储节点和归档节点的存储池。归档副本需要一个仅包含归档节点的存储池。
* 如果使用的存储池包含归档节点，则还应在包含存储节点的存储池上至少维护一个已复制或经过纠删编码的副本。
* 如果启用了全局 S3 对象锁定设置，并且您要创建合规的 ILM 规则，则不能使用包含归档节点的存储池。请参见有关使用 S3 对象锁定管理对象的说明。
* 如果归档节点的目标类型为 Cloud Tiering - Simple Storage Service （ S3 ），则归档节点必须位于其自己的存储池中。请参见 xref:../admin/index.adoc[管理 StorageGRID]。


.相关信息
* xref:what-replication-is.adoc[什么是复制]
* xref:what-erasure-coding-is.adoc[什么是纠删编码]
* xref:what-erasure-coding-schemes-are.adoc[什么是纠删编码方案]
* xref:using-multiple-storage-pools-for-cross-site-replication.adoc[使用多个存储池进行跨站点复制]

