---
permalink: ilm/using-last-access-time-in-ilm-rules.html 
sidebar: sidebar 
keywords: last access time, ilm rule reference time 
summary: 您可以在 ILM 规则中使用上次访问时间作为参考时间。例如，您可能希望将过去三个月查看过的对象保留在本地存储节点上，同时将最近未查看过的对象移动到异地位置。如果您希望 ILM 规则仅应用于上次在特定日期访问的对象，则也可以使用上次访问时间作为高级筛选器。 
---
= 在 ILM 规则中使用上次访问时间
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在 ILM 规则中使用上次访问时间作为参考时间。例如，您可能希望将过去三个月查看过的对象保留在本地存储节点上，同时将最近未查看过的对象移动到异地位置。如果您希望 ILM 规则仅应用于上次在特定日期访问的对象，则也可以使用上次访问时间作为高级筛选器。

在 ILM 规则中使用上次访问时间之前，请查看以下注意事项：

* 使用上次访问时间作为参考时间时，请注意，更改对象的上次访问时间不会触发即时 ILM 评估。而是在后台 ILM 评估对象时评估对象的放置位置，并根据需要移动对象。访问对象后，此操作可能需要两周或更长时间。
+
在根据上次访问时间创建 ILM 规则时，请考虑此延迟，并避免放置时间较短（不到一个月）。

* 如果将上次访问时间用作高级筛选器或参考时间，则必须为 S3 存储分段启用上次访问时间更新。您可以使用租户管理器或租户管理 API 。
+

NOTE: 对于 Swift 容器，始终会启用上次访问时间更新，但对于 S3 存储分段，默认情况下会禁用上次访问时间更新。

+

IMPORTANT: 请注意，启用上次访问时间更新可能会降低性能，尤其是在对象较小的系统中。之所以会影响性能，是因为每次检索对象时， StorageGRID 都必须使用新的时间戳更新对象。



下表总结了对于不同类型的请求，是否为存储分段中的所有对象更新了上次访问时间。

[cols="1a,1a,1a"]
|===
| 请求类型 | 禁用上次访问时间更新时是否更新上次访问时间 | 启用上次访问时间更新后是否更新上次访问时间 


 a| 
请求检索对象，其访问控制列表或其元数据
 a| 
否
 a| 
是的。



 a| 
请求更新对象的元数据
 a| 
是的。
 a| 
是的。



 a| 
请求将对象从一个存储分段复制到另一个存储分段
 a| 
* 否，对于源副本
* 是，对于目标副本

 a| 
* 是，对于源副本
* 是，对于目标副本




 a| 
请求完成多部分上传
 a| 
是，对于已组装的对象
 a| 
是，对于已组装的对象

|===
.相关信息
* xref:../s3/index.adoc[使用 S3]
* xref:../tenant/index.adoc[使用租户帐户]

