---
permalink: ilm/what-cloud-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a cloud storage pool 
summary: 通过云存储池，您可以使用 ILM 将对象数据移动到 StorageGRID 系统之外。例如，您可能希望将不常访问的对象移至成本较低的云存储，例如 Amazon S3 Glacier ， S3 Glacier Deep Archive 或 Microsoft Azure Blob 存储中的归档访问层。或者，您可能希望维护 StorageGRID 对象的云备份以增强灾难恢复能力。 
---
= 什么是云存储池
:icons: font
:imagesdir: ../media/


[role="lead"]
通过云存储池，您可以使用 ILM 将对象数据移动到 StorageGRID 系统之外。例如，您可能希望将不常访问的对象移至成本较低的云存储，例如 Amazon S3 Glacier ， S3 Glacier Deep Archive 或 Microsoft Azure Blob 存储中的归档访问层。或者，您可能希望维护 StorageGRID 对象的云备份以增强灾难恢复能力。

从 ILM 角度来看，云存储池与存储池类似。要将对象存储在任一位置，请在为 ILM 规则创建放置说明时选择池。但是，虽然存储池包含 StorageGRID 系统中的存储节点或归档节点，但云存储池包含外部存储分段（ S3 ）或容器（ Azure Blob 存储）。

下表对存储池与云存储池进行了比较，并显示了一些高级相似之处和不同之处。

[cols="1a,2a,2a"]
|===
|  | 存储池 | 云存储池 


 a| 
如何创建？
 a| 
使用网格管理器中的 * ILM * > * 存储池 * 选项。

您必须先设置存储级别，然后才能创建存储池。
 a| 
使用网格管理器中的 * ILM * > * 存储池 * 选项。

您必须先设置外部存储分段或容器，然后才能创建云存储池。



 a| 
您可以创建多少个池？
 a| 
无限制。
 a| 
最多 10 个。



 a| 
对象存储在何处？
 a| 
在 StorageGRID 中的一个或多个存储节点或归档节点上。
 a| 
位于 StorageGRID 系统外部的 Amazon S3 存储分段或 Azure Blob 存储容器中。

如果云存储池是 Amazon S3 存储分段：

* 您可以选择配置存储分段生命周期，以便将对象过渡到低成本的长期存储，例如 Amazon S3 Glacier 或 S3 Glacier Deep Archive 。外部存储系统必须支持 Glacier 存储类和 S3 POST 对象还原 API 。
* 您可以创建云存储池，以便与支持 AWS 机密区域的 AWS 商用云服务（ C2S ）结合使用。


如果云存储池是 Azure Blob 存储容器，则 StorageGRID 会将对象过渡到归档层。

* 注意： * 一般情况下，不要为用于云存储池的容器配置 Azure Blob Storage 生命周期管理。对云存储池中的对象执行的后对象还原操作可能会受所配置生命周期的影响。



 a| 
什么控制对象放置？
 a| 
活动 ILM 策略中的 ILM 规则。
 a| 
活动 ILM 策略中的 ILM 规则。



 a| 
使用什么数据保护方法？
 a| 
复制或纠删编码。
 a| 
复制。



 a| 
每个对象允许多少个副本？
 a| 
多个。
 a| 
一个副本位于云存储池中，一个或多个副本也位于 StorageGRID 中。

* 注意： * 在任何给定时间，不能将对象存储在多个云存储池中。



 a| 
有哪些优势？
 a| 
可以随时快速访问对象。
 a| 
低成本存储。

|===