---
permalink: fabricpool/best-practices-for-high-availability-groups.html 
sidebar: sidebar 
keywords: fabricPool, high availability group, HA group, active-active, active-backup, cloud tier, best practices 
summary: 在将 StorageGRID 附加为 FabricPool 云层之前，您应使用 StorageGRID 网格管理器配置高可用性 \ （ HA\ ）组。 
---
= 高可用性组的最佳实践
:icons: font
:imagesdir: ../media/


[role="lead"]
在将 StorageGRID 附加为 FabricPool 云层之前，您应使用 StorageGRID 网格管理器配置高可用性（ HA ）组。



== 什么是高可用性（ HA ）组？

为了确保负载平衡器服务始终可用于管理 FabricPool 数据，您可以将多个管理节点和网关节点的网络接口分组到一个实体中，称为高可用性（ High Availability ， HA ）组。如果 HA 组中的活动节点发生故障，则组中的另一个节点可以继续管理工作负载。

每个 HA 组均可提供对关联节点上共享服务的高可用性访问。例如，如果 HA 组仅包含网关节点上的接口，或者同时包含管理节点和网关节点上的接口，则可以对共享负载平衡器服务进行高可用性访问。

要创建 HA 组，请执行以下常规步骤：

. 为一个或多个管理节点或网关节点选择网络接口。您可以选择网格网络接口（ eth0 ），客户端网络接口（ eth2 ）或 VLAN 接口。
+

IMPORTANT: 如果您计划使用 VLAN 接口隔离 FabricPool 流量，则网络管理员必须先配置中继接口和相应的 VLAN 。每个 VLAN 都通过一个数字 ID 或标记来标识。例如，您的网络可能会使用 VLAN 100 传输 FabricPool 流量。

. 为组分配一个或多个虚拟 IP （ VIP ）地址。FabricPool 等客户端应用程序可以使用其中任何 VIP 地址连接到 StorageGRID 。
. 指定一个接口作为主接口，并确定任何备份接口的优先级顺序。主接口是活动接口，除非发生故障。


如果 HA 组包含多个接口，而主接口出现故障，则 VIP 地址将按优先级顺序移至第一个备份接口。如果该接口发生故障， VIP 地址将移至下一个备份接口，依此类推。此故障转移过程通常只需几秒钟，并且速度足以使客户端应用程序不会受到任何影响，并且可以依靠正常的重试行为继续运行。

解决故障后，如果更高优先级的接口再次可用，则 VIP 地址会自动移至可用的最高优先级接口。



== 高可用性（ HA ）组的最佳实践

为 FabricPool 创建 StorageGRID HA 组的最佳实践取决于工作负载，如下所示：

* 如果您计划将 FabricPool 与主工作负载数据结合使用，则必须创建一个至少包含两个负载平衡节点的 HA 组，以防止数据检索中断。
* 如果您计划使用 FabricPool snapshot-only 卷分层策略或非主本地性能层（例如，灾难恢复位置或 NetApp SnapMirror ® 目标），则只能为 HA 组配置一个节点。


以下说明介绍如何为主动备份 HA 设置 HA 组（一个节点为活动节点，一个节点为备份节点）。但是，您可能更喜欢使用 DNS 轮循或主动 - 主动 HA 。要了解这些其他 HA 配置的优势，请参见 xref:../admin/configuration-options-for-ha-groups.adoc[HA 组的配置选项]。
