---
permalink: fabricpool/using-storagegrid-ilm-with-fabricpool-data.html 
sidebar: sidebar 
keywords: FabricPool, requirements, ILM, information lifecycle management, ILM rule, ILM rules, ILM policy, erasure-coding, replication, cloud storage pool, glacier 
summary: 如果您使用 FabricPool 将数据分层到 StorageGRID ，则必须了解创建 StorageGRID 信息生命周期管理 \ （ ILM ）规则以及用于管理 FabricPool 数据的 ILM 策略的要求。您必须确保适用于 FabricPool 数据的 ILM 规则不会造成中断。 
---
= 将 StorageGRID 信息生命周期管理与 FabricPool 数据结合使用
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用 FabricPool 将数据分层到 StorageGRID ，则必须了解创建 StorageGRID 信息生命周期管理（ ILM ）规则和用于管理 FabricPool 数据的 ILM 策略的要求。您必须确保适用于 FabricPool 数据的 ILM 规则不会造成中断。


IMPORTANT: FabricPool 不了解 StorageGRID ILM 规则或策略。如果 StorageGRID ILM 策略配置不当，可能会发生数据丢失。请参见 xref:../ilm/index.adoc[使用 ILM 管理对象] 有关详细的 ILM 说明。

请查看这些准则，以确保您的 ILM 规则和 ILM 策略适合 FabricPool 数据和业务要求。如果您已经在使用 StorageGRID ILM ，则可能需要更新活动的 ILM 策略以满足这些准则。

* 您可以使用复制和纠删编码规则的任意组合来保护云层数据。
+
建议的最佳实践是，在站点内使用 2+1 纠删编码，以实现经济高效的数据保护。纠删编码使用的 CPU 较多，但提供的存储容量明显低于复制。4+1 和 6+1 方案使用的容量小于 2+1 方案。但是，如果您需要在网格扩展期间添加存储节点， 4+1 和 6+1 方案的灵活性将会降低。有关详细信息，请参见 xref:../expand/adding-storage-capacity-for-erasure-coded-objects.adoc[为经过纠删编码的对象添加存储容量]。

* 应用于 FabricPool 数据的每个规则都必须使用纠删编码，或者必须至少创建两个复制副本。
+

IMPORTANT: 如果 ILM 规则在任何时间段内仅创建一个复制副本，则会使数据面临永久丢失的风险。如果某个对象只存在一个复制副本，则在存储节点出现故障或出现严重错误时，该对象将丢失。在升级等维护过程中，您还会暂时失去对对象的访问权限。

* 请勿使用将使 FabricPool 云层数据过期或删除的 ILM 规则。将每个 ILM 规则中的保留期限设置为 " 永久 " ，以确保 StorageGRID ILM 不会删除 FabricPool 对象。
* 请勿创建将 FabricPool 云层数据从存储分段移至其他位置的规则。您不能使用 ILM 规则使用归档节点将 FabricPool 数据归档到磁带，也不能使用云存储池将 FabricPool 数据移动到其他对象存储。
+

NOTE: 不支持将云存储池与 FabricPool 结合使用，因为从云存储池目标检索对象会增加延迟。

* 从 ONTAP 9.8 开始，您可以选择创建对象标记来帮助对分层数据进行分类和排序，以便于管理。例如，您只能在连接到 StorageGRID 的 FabricPool 卷上设置标记。然后，在 StorageGRID 中创建 ILM 规则时，您可以使用对象标记高级筛选器选择并放置此数据。




== FabricPool 数据的 ILM 策略示例

使用此简单的示例策略作为您自己的 ILM 规则和策略的起点。

本示例假设您正在为一个 StorageGRID 系统设计 ILM 规则和 ILM 策略，该系统在科罗拉多州丹佛的一个数据中心内有四个存储节点。此示例中的 FabricPool 数据使用名为 `fabricpool-bucket` 的存储分段。


CAUTION: 以下 ILM 规则和策略仅为示例。配置 ILM 规则的方法有多种。在激活新策略之前，请模拟建议的策略，以确认它将按预期工作，以防止内容丢失。要了解更多信息，请参见 xref:../ilm/index.adoc[使用 ILM 管理对象]。

.步骤
. 创建一个名为 * 的存储池 * 。选择丹佛站点。
. 创建一个名为 *2 加 1* 的擦除编码配置文件。选择 2+1 纠删编码方案和 * DEN* 存储池。
. 创建仅适用于 `fabricpool-bucket` 中数据的 ILM 规则。此示例规则用于创建经过擦除编码的副本。
+
[cols="1a,2a"]
|===
| 规则定义 | 示例值 


 a| 
规则名称
 a| 
2 加上 1 个用于 FabricPool 数据的纠删编码



 a| 
Bucket Name
 a| 
`fabricpool-bucket`

您也可以筛选 FabricPool 租户帐户。



 a| 
高级筛选
 a| 
对象大小（ MB ）大于 0.2 MB 。

* 注： * FabricPool 仅写入 4 MB 对象，但您必须添加对象大小筛选器，因为此规则使用纠删编码。



 a| 
参考时间
 a| 
载入时间



 a| 
放置
 a| 
从 Day 0 存储永久存储



 a| 
Type
 a| 
已进行纠删编码



 a| 
位置
 a| 
DEN （ 2 加 1 ）



 a| 
载入行为
 a| 
平衡

|===
. 创建一个 ILM 规则，以便为第一个规则不匹配的任何对象创建两个复制副本。请勿选择基本筛选器（租户帐户或存储分段名称）或任何高级筛选器。
+
[cols="1a,2a"]
|===
| 规则定义 | 示例值 


 a| 
规则名称
 a| 
两个复制副本



 a| 
Bucket Name
 a| 
无 _



 a| 
高级筛选
 a| 
无 _



 a| 
参考时间
 a| 
载入时间



 a| 
放置
 a| 
从 Day 0 存储永久存储



 a| 
Type
 a| 
已复制



 a| 
位置
 a| 
DEN



 a| 
副本
 a| 
2.



 a| 
载入行为
 a| 
平衡

|===
. 创建建议的 ILM 策略并选择两个规则。由于复制规则不使用任何筛选器，因此它可以是策略的默认（最后）规则。
. 将测试对象载入网格。
. 使用测试对象模拟策略以验证此行为。
. 激活策略。


激活此策略后， StorageGRID 将按如下所示放置对象数据：

* 从 `fabricpool-bucket` 中的 FabricPool 分层的数据将使用 2+1 纠删编码方案进行纠删编码。两个数据片段和一个奇偶校验片段将放置在三个不同的存储节点上。
* 所有其他分段中的所有对象都将被复制。将创建两个副本并将其放置在两个不同的存储节点上。
* 经过纠删编码的副本和复制的副本将保留在 StorageGRID 中，直到 S3 客户端将其删除为止。StorageGRID ILM 不会删除这些项目。

